### ISSUE TITLE
The "address" table needs to be back

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#105]
We note that it would be more efficient/easier for performing address queries, if the complex xalAddress data are mapped onto a separate table `address` like in the current 3DCityDB v4.

**Comment by clausnagel** [comment]
One reason for this is that xAL addresses can be encoded in different ways leading to different representations in the property table. So, retrieving the "road" part of an address might require different queries, which is not wanted.

An alternative approach to having a separate address table could be to map every address to a fixed and predefined set of properties in the property table (so, we would translate the columns of the address table to rows in the property table). We could use an Address ADE for this purpose (like we use it for the 3DCityDB v4).

**Comment by thomashkolbe** [comment]
@clausnagel: I think that is the best way to avoid getting extra tables that again need to be handled differently. We should keep all properties in the PROPERTY table.

**Comment by yaozhihang** [comment]
According to the offline discussion, we decided to keep the `address` table. Address features should be registered in the `feature` table See https://github.com/3dcitydb/3dcitydb/issues/146
