### ISSUE TITLE
set max length of "val_string" to 4000

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#106]
The current length is 256, which is not enough for storing some generic string attribute in real-world data. I'll change it to 4000 which should be OK.

**Comment by muratkendir** [comment]
Need to check that, actually defining as character varying will be enough for postgresql, but not i am not sure about Oracle.

**Comment by clausnagel** [comment]
I think we should even go with the PostgreSQL-specific `text` datatype.

**Comment by yaozhihang** [comment]
agree, according to the [postgreSQL documentation ](https://www.postgresql.org/docs/current/datatype-character.html), using `text` has no bad side effect on performance

**Comment by thomashkolbe** [comment]
I agree to use `text` as datatype for strings in the PostgreSQL version of the 3DCityDB.
