### ISSUE TITLE
How to delate, edit and save an objekt?

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb#11]
Hi !
First of all thank you for this great product! I am using 3DcityDB and still learning a lot!
I wonder how to delete, edit or uppdate an objekt. The Impoter/exporter does´nt show this possibilities..
Is there a tool for editing objects on the fly ? Im am using CityEditor and is great, but still you have to export from 3DcityDB--- import in SketchUp-- edit-export and finally import to the 3DcityDB and then this does´n replace the existing object..
Regards
Abel

**Comment by FxKu** [comment]
Sorry, missed this one (or did I answer by mail?) 
#16 also refers to this, I think.

Actually, the SketchUp workflow has been the initial motivation for the developing an Integrate Plugin for the Importer/Exporter :) The is also a plugin for deleting objects (comercial too). Regarding direct editing, I think this works with BentlyMap. I have high hopes that it will work with QGIS 3 one day.
