### ISSUE TITLE
Update the metatables "aggregation_info" and "objectclass"

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#110]
The following changes should be done for the two tables, since we don't map feature classes onto individual data tables anymore,  
1. drop the column `join_table_or_column_name` from the `aggregation_info` table
2. drop the column `tablename` from the `objectclass` table

Also, the scripts for pre-filling the two tables should also be updated for CityGML 1, 2 and 3 feature classes.

**Comment by yaozhihang** [comment]
This doc should be used as starting point. @muratkendir is this an up-to-date version?
https://github.com/tum-gis/3dcitydb-v5/blob/master/docs/meeting_recordings/2021_11_02_feature_types_and_super_classes_by_space_Kendir.xls

**Comment by muratkendir** [comment]
Yes, it was the latest version, but may still have missing objectclasses. It should be checked again regarding to objectclass table. I have added to docs folder also another version, which additionally consists objectclass names as separate sheet on same document. It shows space_or_boundary_type information more explicitly:
[https://github.com/tum-gis/3dcitydb-v5/blob/master/docs/meeting_recordings/2021_11_09_feature_types_and_super_classes_by_space_Kendir.xls](https://github.com/tum-gis/3dcitydb-v5/blob/master/docs/meeting_recordings/2021_11_09_feature_types_and_super_classes_by_space_Kendir.xls)

**Comment by yaozhihang** [comment]
Thanks @muratkendir. This doc provides a very good overview. 

Since a number of new classes are introduced in CityGML 3.0, we have to assign new IDs to them. Besides, the following questions are raised:

1. Do we need to preserve the deprected CityGML 2.0 classes (e.g. `BuildingWindow`) along with their IDs in the objectclass table?   
2. Shouldn't we re-assign new IDs to the feature classes completely? For example, the value range `0 - 99` can be reserved for the core module, `100 - 199` for Appearance module, `200 - 299` for Construction module etc.

**Comment by clausnagel** [comment]
A mixture of old and new objectclass ids in one table doesn't really make sense for me as it would be based on both CityGML 2.0 and CityGML 3.0. We also want to map the class hierarchy with the objectclass table, and such a mixture would make this difficult if possible at all. And I agree that we should not introduce another table for old ids.

We should focus on a clean v5 schema. Thus, we should populate the objectclass table with new ids only based on CityGML 3.0. The 3DCityDB v5 will be a major version release, so we do not have to maintain backwards compatibility. But still you can define a 1:1 mapping from old ids to new ids, so I don't even see an issue with that.
