### ISSUE TITLE
Update the "index_table"

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#111]
We need to decide which indexes should be registered into the "index_table" additionally:
https://github.com/3dcitydb/3dcitydb/blob/v5-devel/postgresql/SQLScripts/SCHEMA/INDEX_TABLE/INDEX_TABLE.sql

**Comment by clausnagel** [comment]
Well, another question is whether we should maintain this table at all. It is only used by the Importer/Exporter. So, the list of indexes could also be maintained by this tool directly. Would it even make easier for users to extend or edit the list via the Importer/Exporter.

**Comment by clausnagel** [comment]
`index_table` has been dropped for v5.
