### ISSUE TITLE
drop the "grid_coverage" table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#112]
The `grid_coverage` table is never supported by our software e.g. importer/exporter. Let's drop this table for the alpha release and discuss later, if we need to readd this table for the citydb final version 5

**Comment by muratkendir** [comment]
I didn't also noticed any dataset which consists grid_coverage data, but i need to inform you about an important issue: v5 database structure was consisting a column "val_pointcloud". This column has been dropped after a while by following Thomas Kolbe's proposals, but val_grid_coverage kept as it is, which refer to grid_coverage table. So, as i understood point clouds can be stored in 3DCityDB by two methods: MultiPoint geometries or coverages of external LAS/LAZ files. So, i think grid_coverage table can be still useful to store coverage/boundary information of this kind of external point cloud files.

**Comment by clausnagel** [comment]
The `grid_coverage` table as implemented in v4 and proposed for v5 is only meant to store raster data. I suggest to decouple the disucssion about possibly storing metadata for point clouds from this issue.
