### ISSUE TITLE
Purpose of "datatype" column?

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#114]
What is the purpose of the `datatype` column in the `property` table?

**Comment by clausnagel** [comment]
I see the following issues:

1. I think we should keep the database free from encoding-specific stuff like GML type names. We could store the type name as defined in the conceptual model - but that implicitly follows from the qualified name of the property already.
2. The type name is stored redundantly with every instance of a property. This will let the property table grow. We should have a good use case why we need this.

This needs more discussion.

**Comment by muratkendir** [comment]
It is a column to keep properties decomposable. For example. lod2Solid properties in the table have namespace values as "core", name values as "lod2Solid" and they have "gml:Solid" as datatype values. So, feature_id, namespace, name and index numbers are enough to define/differ geometries, but they are still keeping gml definitions on same table.

**Comment by clausnagel** [comment]
Not sure whether this speaks in favor of keeping or dropping the colunm?

In any case we should keep this independent from GML.

**Comment by muratkendir** [comment]
I feel myself very conservative at this moment :) So, i prefer to keep datatype column.

**Comment by yaozhihang** [comment]
agree with @clausnagel
