### ISSUE TITLE
val_string and val_uri

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#115]
Why do we need both `val_string` and `val_uri` as columns of the `property` table? An URI could also be stored in `val_string`. Whether it's a URI or a simple string should be clear from `data_valtype`, shouldn't it?

**Comment by yaozhihang** [comment]
The `val_uri` column is used for storing the `core:GenericName` and `core:ExternalReference`. See the sheet table `Datatype mappings` in this doc. 
https://github.com/tum-gis/3dcitydb-v5/blob/master/docs/meeting_recordings/2021_10_19_3DCityDB_Version_5.0_Kolbe.xlsx

**Comment by clausnagel** [comment]
Ok, thanks, makes sense then.
