### ISSUE TITLE
Add support for free format address representations

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#117]
xAL supports free format address representations. You can have one or more `<AddressLine>` elements and each address line stores a simple string. There is no specification on the syntax or semantics of the strings, so this is very generic but also very flexible. I think we should support this somehow. Maybe we could add a `free_text` column to the `address` table? The only question would be how to store multiple address lines. I would like to avoid another predefined delimiter. We could, for example, use JSON as datatype and store the address lines as array.

Maybe a generic JSON column would make sense anyway. Because the current columns of the `address` table are not sufficient for all the different ways of how addresses are represented in different countries. Additional address properties might therefore be stored in the JSON type.

**Comment by yaozhihang** [comment]
So, we add a column `address_lines` in JSON type?

**Comment by yaozhihang** [comment]
Done with 41f9b12

**Comment by clausnagel** [comment]
Thanks, @yaozhihang, this is good as a starting point for the alpha release. Will keep the issue open so that we can continue the discussion after the alpha release.
