### ISSUE TITLE
Simplify the "ADE"  Table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#118]
Since we have a very static and generic table structure for storing CityGML ADE data, the `ADE` table can be simplified by dropping some columns e.g. `db_prefix`, `xml_schemamapping_file` etc.

**Comment by gioagu** [comment]
I agree. If we make it to really map all objects to existing tables, then we are fine.
See also the parallel discussion on how to possibly (re)name the (current) FEATURE table which would contain also objects that are not features.
