### ISSUE TITLE
How can I put these 3D-Tiles (i3dm, b3dm, pnts) into 3DCityDB?

### ISSUE THREAD

**Issue by salutonalpha** [3dcitydb/3dcitydb#12]
I am quite new to 3DCityDB.

I have many gltf building models, and I have converted these models into 3D-Tiles(b3dm) using 3d-tiles-tools, but how should I to store these b3dm into 3DCityDB? And How can I query 3d-tiles data from 3DCityDB?

Many thanks

**Comment by yaozhihang** [comment]
To create a valid 3D-Tiles datasets, your b3dm data must be organized in a proper spatial data structure which can be formally represented using a so-called "tileset.json" file. More details can be found here:
https://github.com/AnalyticalGraphicsInc/3d-tiles#introduction

Deploying 3DTiles datasets only requires an ordinary web server, i.e. Apache without the need to use 3DCityDB. Once your 3D-Tiles datasets have been uploaded to a web server, the URL of the file folder, where the root tileset.json file is located, can be passed to Cesium Virtual Globe which allows to dynamically stream and visualize the tiled datasets according to the camera view perspective. Code  Examples can be found here:
https://github.com/AnalyticalGraphicsInc/cesium/blob/3d-tiles/Source/Scene/Cesium3DTileset.js#L146

**Comment by salutonalpha** [comment]
Thank you for your reply.

![_meitu_1](https://cloud.githubusercontent.com/assets/28304505/26707340/cb096164-4776-11e7-8ffd-fc494bf7445c.jpg)

I would like to know how can I convert these building models which have been organized in 3DCityDB to 3DTiles data.

**Comment by yaozhihang** [comment]
Our open-source 3DCityDB software package is currently not able to produce 3D-Tiles datasets. 
Alternatively, the company [virtualcitySYSTEMS ](http://www.virtualcitysystems.de/en/), who is one of the key development partners of 3DCityDB, provides a commercial software tool allowing to convert CityGML to 3D-Tiles datasets directly.

**Comment by thomashkolbe** [comment]
We will need to do a major update on the 3DCityDB Importer/Exporter regarding the export of visualization formats as soon as we have included the support of Application Domain Extensions. Hence, there is a good chance that we will address the generation of 3DTiles in the course of these developments. However, this requires a huge development and implementation effort for us, and we first need to see where we can get the financial support for this (- any idea on this? ;-) ). In the meantime you can either stick with the current solution (export of tiled glTF files - which still works great with the 3DCityDB webclient) or to choose another, possibly commercial solution for this task as mentioned by Zhihang Yao in the preceding post.

**Comment by clausnagel** [comment]
Closing this issue as the question seems to be answered. Feel free to reopen.
