### ISSUE TITLE
add column "val_date_offset" to the property table

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#122]
During the CityGML import, the time attrbitue value e.g. `2022-02-01T00:00:00+05:00` will be automatically translated to the time of the database system. For example, if the database system uses UTC timezone, then the time will be stored in the `val_date` column as `2022-01-31T19:00:00+00:00`. During the CityGML export, the exporter doesn't know, which time offset should be used for rebuilding the original time attribute value. Hence, we need an additional column `val_date_offset` to store the time offset information.

**Comment by clausnagel** [comment]
To provide more background for this request: this wouldn't be an issue if my machine and the database server run in different timezones but I consistently run imports and exports from my machine? It would make a difference though if I import from my machine but do an export on the database server?
