### ISSUE TITLE
DROP column citymodel_id in table feature

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb#130]
As far as I can guess, column citymodel_id in table feature is a leftover from v. 4 and should be deleted, as happened to all citymodel-related tables. Right?

**Comment by muratkendir** [comment]
If there is no any opposite opinion for that, i am totally agree with drop citymodel and cityobject_member tables and all related "citymodel_id" columns in relavant tables. I was thinking that maybe they could be a possibility to use different coordinate systems in same database and schema, but it looks like impossible (at least on the OracleDB side).

**Comment by clausnagel** [comment]
`citymodel_id` will be dropped.
