### ISSUE TITLE
Add namespace column to objectclass

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#138]
Or maybe to ade table?

**Comment by yaozhihang** [comment]
better into `objectclass` table, because an ADE could have multiple schemas/namespaces.

**Comment by yaozhihang** [comment]
Should we name the column `namespace_prefix` and point to the `prefix` column of the `namespace` column.
similar to hier https://github.com/3dcitydb/3dcitydb/issues/139 ?

**Comment by yaozhihang** [comment]
Or, rename the column to `namespace_id` pointing to the `id` column of the `namespace` table?

**Comment by yaozhihang** [comment]
done with 5c57c07a
