### ISSUE TITLE
introduce new table "namespace"

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#139]
`Property` Table: rename the column `namespace` to `namespace_prefix` and it can be a FK pointing to the `prefix` column of the new `namespace` table.

`namespace` table columns: `id`, `prefix`, `namespace`

**Comment by yaozhihang** [comment]
done with https://github.com/3dcitydb/3dcitydb/commit/057aa4a2f2410d1cf3f6fe59c2bf31f78e692eed

**Comment by yaozhihang** [comment]
Reopen this ticket. There is an issue if we use `namespace_prefix` as FK, because the namespace prefix could be non-unique in the `namespace` table. For example,registering two ADEs: UrbanPlanningADE v1.4 and UrbanPlanningADE v1.5 into the `namespace` table.

My proposal is to rename the `namespace_prefix` to `namespace_id`. It should be a FK pointing to the `id` column of the `namespace` table.

**Comment by yaozhihang** [comment]
In general, the wording `prefix` is still XML specific. An alternative could be `abbreviation` or `alias` etc.

**Comment by clausnagel** [comment]
I like `alias`

**Comment by yaozhihang** [comment]
One more question: what should be the alias for the Building module? According to the CityGML Conceptual Model, the alias should be `Building`. From the GML encoding perspective, the alias should then be `bldg`. So, I guess we have to use `Building` as alias.

**Comment by thomashkolbe** [comment]
`alias` is also fine with me. But we should stick to the prefixes of the GML encoding, hence for buildings it should be `bldg`.

**Comment by yaozhihang** [comment]
agree
