### ISSUE TITLE
Are we sure to remove "tablename" in objectclass table?

### ISSUE THREAD

**Issue by muratkendir** [3dcitydb/3dcitydb#153]
I have already removed "tablename" column from objectclass table and also added a backup mechanism which dump existing objectclass table and saves as a file. (in upgrade tool)

I am not sure, if tablename is unnecessary or not. When we import an ADE to 3DCityDB, then we insert new objectclasses to the existing table. Since we have naming convention for CityGML domain, we decided that "tablename"  column is unnecessary. In the meantime, i don't know if we would be able to get/query table names for ADE based objectclasses.
Please see picture below:
[https://drive.google.com/file/d/1NcstNcVVpypBq1TbLA21uCNAtq06KDcZ/view?usp=sharing](https://drive.google.com/file/d/1NcstNcVVpypBq1TbLA21uCNAtq06KDcZ/view?usp=sharing)

**Comment by yaozhihang** [comment]
Similar to the standard CityGML classes, ADE classes and their properties will always be mapped onto the `feature` and `property` table. for 3DCityDB v5. So we don't need the `tablename` column anymore.  Feel free to reopen this ticekt if you have any further questions.
