### ISSUE TITLE
Error in delete functions with data in table generalization

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb#156]
Hi guys!

I think I have found a bug in the delete functions. I am using 3DCityDB v. 4.3
In short: if the FK are written in the GENERALISATION table, the delete scripts forget to delete them, therefore the process fails. 
I add a small dataset to reproduce the error.

Load it (EPSG: 28992) and run either of :

SELECT citydb.del_cityobject(id) FROM citydb.cityobject WHERE gmlid = 'NL.IMBAG.Pand.1742100000007906';
SELECT citydb.del_building(id) FROM citydb.cityobject WHERE gmlid = 'NL.IMBAG.Pand.1742100000007906';

Attached a small test file.

[3dbag_v210908_fd2cee53_482.zip](https://github.com/3dcitydb/3dcitydb/files/10039652/3dbag_v210908_fd2cee53_482.zip)

**Comment by yaozhihang** [comment]
Thanks @gioagu good catch. We've fixed this issue here ff266bc87e5056a03ad407db69c191326890b413 for the upcoming release 4.4.
