### ISSUE TITLE
Rename val_is_reference to val_reference_type

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#160]
The column `val_is_reference` of the table `property` will be used to store XLink information. The current name suggests that it takes a boolean value. However, as the `IS_XLINK` column of the current 3DCityDB v4 shows, a boolean value is not sufficient but we need to be able to store the type of the reference: `null` = no reference, `1` = global reference, `2` = local reference. For the 3DCityDB v4, we decided to keep the name `IS_XLINK` to avoid a major change of the database schema. For the 3DCityDB v5, I propose to rename `val_is_reference` to `val_reference_type`.

**Comment by yaozhihang** [comment]
done with 8c0111d
