### ISSUE TITLE
Remove index_number from property

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#161]
The `index_number` column of the `property` table is meant to store the order of attributes sharing the same name. For example, assume a feature has four `gml:name` attributes. Then the attributes would be assigned the index numbers 1, 2, 3, and 4. Based on these index numbers, the original order of the `gml:name` attributes can be restored when exporting the feature. Or queries involving the position of the attribute can be supported (e.g., "give me all buildings whose second `gml:name` has the value ABC").

However, managing the index number introduces a huge overhead. For instance, assume we want to add another `gml:name` attribute to the same feature in the above example. We first must calculate the next index number, which requires querying the highest index. Or assume, we want to delete the `gml:name` at index 2. This would require decrementing all index numbers higher than 2. Or assume, we want to insert another `gml:name` between 1 and 2. This requires to first increment all index numbers higher than 2.

If we just use the PK as "index number", we are also able to export the `gml:name` attributes in their original order. And we can also support queries involving the position of an attribute. And we can easily add more `gml:name`  attributes at the end of the sequence. The only thing we couldn't easily support is to add a new `gml:name` between two already existing ones.

We never had the requirement to insert a new attribute between two already exisiting ones for the 3DCityDB v4. Imho, the overhead for managing the index number is too high just to be able to support this (non) use case. I also think the index number makes it more difficult to access and change the property table with external tools such as FME or QGIS.

I therefore propose to remove the `index_number` column from the `property` table.

**Comment by gioagu** [comment]
Shouldn't this issue be related to #163?
Lots of array functions already exist in DBs that - if really needed - can take care of this. So, IMO, I agree with removing the index_number. Claus' reasoning makes sense, as well as the lack of support for the potetial "non use case".

**Comment by muratkendir** [comment]
In my situation, i am using following functions to aggregate and split multiple values (mostly in gml:name, gml:function, gml:usage): STRING_TO_ARRAY, UNNEST, ARRAY_POSITION and STRING_AGG. Most important thing is that i need to recombine these rows by considering their first orders. To do that, i am using ORDER BY clause with "index_number"s. I think same clause with primary keys would be more inefficient.

For Exp: 
- [Converting strings to array](https://tumde-my.sharepoint.com/:i:/g/personal/murat_kendir_tum_de/EY-PWemwIRxNtRSXHMGv_-8BtQ4bsDhPLK8HJFCQmwSOaw?e=fXqYl1)
- [Splitting converted array to multiple rows(Unnest)](https://tumde-my.sharepoint.com/:i:/g/personal/murat_kendir_tum_de/ETZfBmDsOQVMkL2U_JZHMb0BQHpnwEYY_och6XKtetse3Q?e=3QvNTE)
- [Obtaining original order number as index number](https://tumde-my.sharepoint.com/:i:/g/personal/murat_kendir_tum_de/EV5RRpswmZBFsrImjQk04CwBK42K3Cfh_-1Q119xwYcKfw?e=XSdeVg)
- [Combining them again just as in original order(used in Views)](https://tumde-my.sharepoint.com/:i:/g/personal/murat_kendir_tum_de/ETMtyiD2lTBLkjA9y_zC_ywBQ-D7BP34TPTqLMvbOjEmhg?e=n5cUeQ)

**Comment by clausnagel** [comment]
@muratkendir, thanks for your input. Why should your query be more unefficient using the PK? Also, I guess your use case is to mimic the 3DCityDB v4 based on v5, right? I wouldn't regard this as default use case for v5. I think it's OK if this would be a bit slower when using the PK (but still I'm not sure whether it really is slower). A user could also materialize the view to make it faster.

**Comment by muratkendir** [comment]
@clausnagel  I checked again with my view & materialized view creation scripts. (I tested it by querying 50.000 buildings from the view using only "id" or "index_number"+"feature_id") My findings/opinions are below:
- If the order of multiple name values not changed, then there is no any significant performance change. (Also same for materialized views.)
- On the other hand, adding a new gml:name value and changing the order of multiple values scenario has been never tested with considering primary keys. (also acceptable for others, such as function, usage, veg:species etc. ) Since property>id column always used with sequence, i think it would be harder to manipulate the order of name/function/usage values.
- One more thing, which is not less important, the uniqueness of properties on the upgrade scripts is checked by "feature_id + index_number + namespace + name" bundle. Without using index_number i can't proceed the uniqueness of property data.

**Comment by muratkendir** [comment]
@clausnagel Primary Key of property table is already standalone unique. In the meantime, primary key of property table is created after import process, just after checking uniqueness of property sets. Otherwise, many duplicated values will be stored in property table.

**Comment by clausnagel** [comment]
Not sure that I get the problem with the upgrade scripts. But when you need some index number to ensure uniqueness in this process, then maybe better use a temporary table just for this process.

**Comment by muratkendir** [comment]
"Every feature should have only one property with the same namespace:name type." This expression summarizes the situation regarding to property uniqueness. So, the combination of "feature_id", "namespace" and "name" should be unique. The only exception to apply this rule is multiple values which may stored in "name", "function", "usage", "veg:species".  These values can be split into multiple rows with different index_number values. So, with the additional "index_number" column we can provide uniqueness for the property table.

**Comment by clausnagel** [comment]
> "Every feature should have only one property with the same namespace:name type." 

Why?

>  So, with the additional "index_number" column we can provide uniqueness for the property table.

I still don't see why we need `index_number` for this. 

I suggest to discuss and clarify this offline first.

**Comment by yaozhihang** [comment]
According to the offline discussion, drop the column `index_number`.
