### ISSUE TITLE
Do we really need data_valtype?

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#162]
What is the real benefit of the `data_valtype` column of the `property` table?

I doubt that we need it. What we need is a documentation on how specific data types should be represented in the `property` table and which columns shall be used to store the value(s). For example, we must define how a `gml:name`, a `core:lod1Solid` or a `con:height` must be represented. And this documentation should be machine-readable because we need it to be able to map queries expressed in CityGML to a correct SQL statement. I don't see how `data_valtype` can help here. Moreover, we don't know all possible data types a priori (just think of data types defined in an ADE or other encodings besides CityGML that we want to store in the 3DCityDB v5).

And if `data_valtype` is just meant to indicate where to look for the value for a specifc row of `property`, then I still question whether this is useful. For example, assume `data_valtype = 1` means the value is stored in `val_string` and `data_valtype = 2` means the value is stored in `val_double`. If the row contains a `gml:name` (which I know from the `name` and `namespace`), I would always look in `val_string` to find the value even is `data_valtype` is set to 2. 

I would like to start a discussion why we need `data_valtype` and whether we shouldn't better remove it.

**Comment by gioagu** [comment]
Agree with removing it, but we must come up with machine-readable rules. Are there already examples regarding this?

**Comment by muratkendir** [comment]
I guess removing data_valtype could be a problem because of "cityobject_genattrib" values which may transferred from a CityDBv4 dataset. For Exp: [CityDBv4_generic_attribute](https://tumde-my.sharepoint.com/:i:/g/personal/murat_kendir_tum_de/EbBPdzkYwLFDqfLGVKLR90cB1ZEh_troaai06mzdAuHdEg?e=MHvhuL) , [CityDBv5_property](https://tumde-my.sharepoint.com/:i:/g/personal/murat_kendir_tum_de/EaAnmFQ3dO1DhQuSZlUtqboBpyQj-Qm6TtwScARKwNRPkA?e=0Emnzb)

**Comment by clausnagel** [comment]
Generic attribute types and their value columns:

| Generic attribute type  | Value column(s) |
| - | - |
| gen:CodeAttribute  | val_string, val_codespace |
| gen:DateAttribute  | val_timestamp |
| gen:DoubleAttribute  | val_double |
| gen:IntAttribute | val_int |
| gen:MeasureAttribute | val_double, val_uom |
| gen:StringAttribute | val_string |
| gen:UriAttribute | val_uri |
| gen:GenericAttributeSet| none (but has child attributes)  |

So, the attribute types can be distinguished based on the value columns used.

There is only one possible conflict because the `codeSpace` attribute for `gen:CodeAttribute` is optional according to the CityGML 3.0 XML schema. If not provided in a dataset, one couldn't tell the difference between a `gen:CodeAttribute` and a `gen:StringAttribute` if `val_codespace` is set to NULL. 

We could easily require setting `val_codespace` to something else than NULL to make it unambigious again like, for instance, `"<unknown>"` or to the namespace of the Generics module. And, moreover, how likely is it that one would use a `gen:CodeAttribute` without providing a `codeSpace`?

We could also keep `data_valtype` just for the generic attribute types (but better rename it to something like `generic_valtype` then). But I would say it's absolutely required to have it.

**Comment by clausnagel** [comment]
@gioagu 

> Agree with removing it, but we must come up with machine-readable rules. Are there already examples regarding this?

No, there are no examples yet. I think of something similar like the `schema-mapping.xml` file of the 3DCityDB v4. But it would be much more lighweight because we just have to store the mapping of XML elements and attributes onto columns of `property`. And the mapping of complex attributes onto self-joins with `property`, of course.

Would be nice to have one mapping language that would work with other encodings such as (Geo)JSON as well.

Do you have ideas / recommendations?

**Comment by clausnagel** [comment]
@muratkendir, just to avoid confusion: the main purpose of the mapping I have in mind is to define how specific data types are represented in the `property` table. Of course, this information can also be used in a transition from v4 to v5, but this is not its primary intention.

The fact that different data types will use the same (combination of) value column(s) is not an issue. We can unambiguously distinguish them by their `name` and `namespace`.

The difference with generic attributes is that `name` does not store the XML element name of the generic attribute but its user-defined name. So, we only know that we deal with a generic attribute due to the `namespace`. But we can't tell whether it's a `gen:CodeAttribute` or a `gen:StringAttribute` by just looking at the combination of `name` and `namespace`. That's why we additionally have to check the value columns as shown in my table. For all other attributes, this is not required.

**Comment by muratkendir** [comment]
Just wanted to discuss the easiness of data type distinguishing by using "data_valtype" column. I am also supporting to keep this data in an explicit representation on database, otherwise i think that it could become confusing for the other users in the future and may need complicated switch-case/if-else conditions to convert the data.

**Comment by clausnagel** [comment]
> Just wanted to discuss the easiness of data type distinguishing by using "data_valtype" column.

As mentioned in my initial post, I would only agree under the assumption that we know all data types a priori and, thus, have a fixed list of `data_valtype` values. But ADEs, for instance, can define their own data types which are not on our list. For example, assume we have a list of 100 known data types numbered from 1 to 100. Let an ADE define a new data type. We cannot use a `data_valtype` value from our list for it. So, let's pick 101 as its `data_valtype` value.

Now, just by looking at the number 101, you can't tell which value columns in `property` are required to store the value or whether we even need more than one row in `property`. What you need is an additional documentation (machine-readable or not) that provides this information. And if you already have this documentation, what is the additional value of storing the number 101?

Let's make the example a bit more complicated. Assume we have two 3DCityDB instances A and B. And let's assume we use ADE-1 with A and ADE-2 with B. And, finally, let's assume that both ADEs define their own data types. Then, as a consequence, the `data_valtype` 101 might have completely different meanings in A and B. So, again, we need a documentation.

**Comment by yaozhihang** [comment]
According to the offline discussion, drop the `data_valtype` column. We need a database function to tell how complex attributes should be mapped onto columns of property table. see #169
