### ISSUE TITLE
Rename geom_properties column

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#164]
The column name `geom_properties` of the table `geometry_data` uses the abbreviation "geom" for "geometry". It's not quite clear why "geom" is used here wheras all other column names related to geometry use "geometry". 

Either rename the column to "geometry_properties" or simply to "properties". It should be clear that it stores geometry properties because it is part of the `geometry_data` table.

**Comment by yaozhihang** [comment]
We had the discussion during our offline-meeting at TUM and the decision was here #141, because the "properties" sounds too _generic_. Maybe "geometry_properties" could be a good alternative.

**Comment by clausnagel** [comment]
Good point, thanks. Then I prefer `geometry_properties` just to be consistent with other column names.

**Comment by yaozhihang** [comment]
done with 8c0111d
