### ISSUE TITLE
mimeType inconsistency

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#167]
The `implicit_geometry` table has a column `mime_type` but lacks a column to store the `codeSpace` of the mimeType.

The `tex_image` table also has a `tex_mime_type` column but additionally offers a `tex_mime_type_codespace` column.

This should be harmonized. The preferred way is to add a `mime_type_codespace` column to `implicit_geometry`.

**Comment by yaozhihang** [comment]
done with 8c0111d
