### ISSUE TITLE
New name for Objectclass table

### ISSUE THREAD

**Issue by muratkendir** [3dcitydb/3dcitydb#170]
As you may know, we gave new ID numbers for every new or inherited object classes in the new "objectclass" table. 
To do that, i have created a table to show and map the relations between old "objectclass" table rows and new ones. (see [link](https://tum-gis.github.io/3dcitydb-v5/other_documents/others/mapping_objectclass_doc/))
Additionally, i have created a diagram to visualize the sub-super class hierarchy in the new objectclasses. (see[link](https://tum-gis.github.io/3dcitydb-v5/schema/other_visuals/others/new_objectclasses/new_objectclasses_and_inheritance_relations.html))

However, we have serious problem about "objectclass" table, which will be exposed after using old v4 tools with the new database. 
In a particular moment after running upgrade scripts users can re-populate them and ignore new tables to read.
Only exception to read old data is "objectclass" table. (We used "t_mapping_objectclass" table to re-populate the data of views)

That's why i want to offer to change the name of new objectclass table
   or we can add new objectclass rows by specifying sequential ID numbers starting from 1000 (or more bigger value).

Note: I don't have any suggestion for a new name.

**Comment by yaozhihang** [comment]
Hm, This is not a problem in the current v5 schema. The Upgrade-Skripts should be able to solve such kinds of conflict problem by itself.

**Comment by muratkendir** [comment]
Usually schemas does not include the problems, but the data does.

**Comment by yaozhihang** [comment]
The `Appearance` table name is also used in both v4 and v5, and will also cause the similar issue? If yes, you will also want to change the `Appearance` table name vor v5?

**Comment by muratkendir** [comment]
Ok, i fixed this problem with a temporary solution, but also planning to implement another solution in following weeks.
