### ISSUE TITLE
Adeid in ADE table

### ISSUE THREAD

**Issue by muratkendir** [3dcitydb/3dcitydb#171]
Current columns of ADE table is consisting:
id, adeid, name, description, version [see link](https://tum-gis.github.io/3dcitydb-v5/schema/dbschema_v5_devel/dbschema_v5_devel/#table-ade)

Is adeid column neccessary in ADE table?

**Comment by yaozhihang** [comment]
Good point. I also see no necessity.

**Comment by clausnagel** [comment]
Then let's remove it.
