### ISSUE TITLE
Extend the column "appear_to_surface_data"

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#172]
The table `appear_to_surface_data` can be seen as a specific _property_ table for appearance features, and It only contains the SurfaceData property. Since this property can also be a local or global reference, we need at least one more column `val_reference_type` in this table.
I would also like to add one column "id" as the primary key for the table. This allows the importer much easier with higher performance to resolve the global references.

**Comment by clausnagel** [comment]
I agree. If we want to support XLinks to surface data objects, then we should add these columns.

**Comment by yaozhihang** [comment]
I added the two columns to the table `appear_to_surface_data` (see 52ce3703decc8861d143d481790206a384751e71 and  856b33ce94b6c454e62539caa9a6984144c2857d) to make the Importer/Exporter to support XLinks.

**Comment by clausnagel** [comment]
Closing since implemented. `val_reference_type` should be renamed if we implement #201
