### ISSUE TITLE
rename id column in address table

### ISSUE THREAD

**Issue by muratkendir** [3dcitydb/3dcitydb#174]
If we will just copy **id** of **feature** into **address** table (just like our former storage strategy in CityDBv4),
then we need at least to rename the column name as "_feature_id_".
[address table](https://tum-gis.github.io/3dcitydb-v5/schema/dbschema_v5_devel/webview/v5_devel_web.html#citydb.address)

**Comment by clausnagel** [comment]
Good catch. I'd rather say the foreign key constraint to `feature` is wrong and should be removed. Like in v4, the `address` table has its own sequence for the `id` column which is used to populate the value. Also the appearance tables in v5 have similar foreign keys to `feature` although they have their own sequences. These foreign keys should be removed as well.

**Comment by yaozhihang** [comment]
According to the off-line discussion at TUM last year, the foreign key constraint to `feature` should be kept. https://github.com/3dcitydb/3dcitydb/issues/105. The sequence `address_seq` is wrong and must be removed.

**Comment by clausnagel** [comment]
Thanks @yaozhihang for pointing to this. In this case, `id` should not be renamed in my opinion because an address is an feature and does not reference a feature.

**Comment by yaozhihang** [comment]
Also good catch @clausnagel, the foreign key to the `feature` table should be removed from the `appearance`

**Comment by muratkendir** [comment]
We might add **gmlid** to the address table, because its missing in the current schema.

**Comment by yaozhihang** [comment]
According to the offline-discussion on 10.03.23, we decided to drop the address table again. This ticket is not relevant anymore. So close it.
