### ISSUE TITLE
Installing the Energy ADE 2.0 on 3DCityDB 4.4.0 breaks delete functions

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb#178]
Installing (and also uninstalling) the Energy ADE 2.0.0 with the Importer/Exporter breaks the delete functions, at least in version 4.4.0 of the 3DCityDB (which I am using). I am not sure if this bug affects also other ADEs...

Proof:

1) Start with a citydb schema WITHOUT the Energy ADE.
Load the data provided in the attached file.
Try to delete some buildings, all is fine. E.g.:

```
WITH s AS (
	SELECT array_agg(foo.id) AS co_id_array
	FROM (
		SELECT b.id FROM citydb.building AS b
		WHERE b.objectclass_id = 26
		LIMIT 5) AS foo
	)
--SELECT s.co_id_array FROM s;
SELECT citydb.del_building(s.co_id_array) FROM s;
```

2) Install the Energy ADE 2.0.0. Run the same query. It fails.

3) Uninstall the Energy ADE 2.0.0. Run the same query, It still fails.

The attached CityGML file contains 101 buildings.

G

PS. Not sure if this issue is best here or in the overall 3DCityDB repo...

[3dbag_v210908_fd2cee53_482.zip](https://github.com/3dcitydb/energy-ade-citydb/files/10766353/3dbag_v210908_fd2cee53_482.zip)

**Comment by yaozhihang** [comment]
Hi @gioagu, sorry for this late feedback again. 
Are you sure you are using the latest version 3DCityDB v4.4? I can reproduce the problem with the earlier version v4.3, but the v4.4 works well in my tests, because a bug has already been fixed ff266bc  in the v4.4.

**Comment by gioagu** [comment]
Hi @yaozhihang 

You are right. I repeated the tests on a freshly installed version 4.4 and the bug did not occur.
I wonder what went wrong the first time, I am sure I was using version 4.4, but I think it had been upgraded from a previous version, while now it was installed from zero.

You can close the bug, I will notify you if I experience the issue again.

Thanks!

**Comment by yaozhihang** [comment]
Thanks @gioagu for your feedback. Feel free to reopen this ticket if the bug happens again.
