### ISSUE TITLE
add missing NOT NULL constraints

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb#18]
During the development of the delete script generator I found that the schema of the 3DCityDB is missing some NOT NULL checks on several columns:

- objectclass_id: This field has to be set, so NOT NULL makes sense
- %root%: Any root column in tables where tree hierarchies are stored is as least set to same value as the ID, so NOT NULL makes also sense here (+ it is also important for the delete script generator to choose the parent column for self recursions, because it can be NULL in our case)
- Some feature classes can have different parents such as boundary surface with building, building_installation or room. At least one of the foreign key column has to be set. Therefore, we could add a CHECK constraint. Yet, I don't know how this would affect the performance of imports.

**Comment by FxKu** [comment]
The new Importer/Exporter will allow for importing CityGML with flat hierarchies. That means weak entities such as boundary surfaces can be on the same lever as their parent e.g. a building. Putting a NOT NULL constraint on `root_id` columns or fk columns to parent entities would make the import much harder. Therefore, we won't add new constraints and remove existing ones.

This does not affect the objectclass_id column. I still think, it's reasonable to enforce NOT NULL here.

**Comment by yaozhihang** [comment]
It makes sense. Fix is done here https://github.com/3dcitydb/3dcitydb/commit/48803b31b72d380bf87b9dd1bd9685176b90eb80
