### ISSUE TITLE
Rename "ade" to "extension"

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#181]
The word `ade` is still CityGML speicifc. Better to rename it to `extension`. For example, rename the table `ade` to `extension` and rename the column name `ade_id` to `extension_id`

**Comment by thomashkolbe** [comment]
We should keep it like that. If you want to extend another datamodel, it would also has to offer an ADE mechanism.

**Comment by clausnagel** [comment]
I agree with @thomashkolbe . I think "Application Domain Extension" is generic enough.

**Comment by yaozhihang** [comment]
thanks for the comments. Let's keep it and close this ticket.
