### ISSUE TITLE
lod column is of type numeric instead of integer in relief_* tables

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb#183]
Not sure if it's intentional or not.
In citydb 4.x, I have noticed that in tables **relief_feature** and **relief_component**, the lod column is of type numeric instead of - as I'd expect - integer.
Intentional or mistake?

GA

**Comment by yaozhihang** [comment]
The numeric type has been used since many versions. I cannot remember if it is an intention. I also think Integer is better here.

**Comment by thomashkolbe** [comment]
That is not intentional. Could be changed to integer. However, if we want to possibly support also other LOD names like LOD 2.1 in the future, it might even be advisable to change all LOD qualifier attributes to datatype string/varchar.

**Comment by clausnagel** [comment]
Will not be changed for v4.x. In v5, the "lod" property of geometries will be stored as "string" to support even more generic labels for geometries.
