### ISSUE TITLE
Namespace Aliases of Versioning and PointCloud

### ISSUE THREAD

**Issue by muratkendir** [3dcitydb/3dcitydb#185]
If you are planning to use prefilled namespaces:
- Alias for Versioning is "vers" (regarding to [this](https://github.com/TatjanaKutzner/CityGML-3.0/blob/master/Encoding/versioning.xsd))
- Alias for PointCloud is "pcl" (regarding to [this](https://github.com/TatjanaKutzner/CityGML-3.0Encodings/blob/master/CityGML/Schema/pointCloud.xsd))

I need to use prefilled namespace tables in the upgrade scripts, that's why i have added also "gml", "xlink" and "xAL" as namespaces to the insertion scripts:
```
INSERT INTO namespace(id, alias, namespace) VALUES (2, 'gml', 'http://www.opengis.net/gml/3.2/');
INSERT INTO namespace(id, alias, namespace) VALUES (1800, 'xAL', 'http://schemas.opengis.net/citygml/xAL/');
INSERT INTO namespace(id, alias, namespace) VALUES (1900, 'xlink', 'http://www.w3.org/1999/xlink');
```

**Comment by clausnagel** [comment]
We will need prefilled namespaces, yes. However, we are currently discussing to not use CityGML/GML/XML-specific namespaces anymore but to define and use 3DCityDB-specific namespaces instead. We see some important advantages for this approach.

**Comment by thomashkolbe** [comment]
Hi Claus, I am not sure if I understand what you mean. In general, we should stick to the official CityGML namespaces and their abbreviations. Otherwise we should discuss this in an online meeting.

**Comment by clausnagel** [comment]
@muratkendir, please share examples why you would need the GML and XLink namespaces.

**Comment by muratkendir** [comment]
For 'gml' namespace: All Solid Geometries, Multi Surfaces and the "gml:Lenght" elements  in con:Height  complex property need to be saved with "gml" namespace.
For 'xAl' namespace: XALAddress Datatype is not explained in detail, but all leafs of the core:Address need to be saved with xAL namespace, such as ThoroughfareName, ThoroughfareNumber, PostBoxNumber, PostalCodeNumber, LocalityName, CountryName and the new address details elements like FreeTextAddress.
For 'XLink' namespace: Since we have decided to save xlink's as redundant data in the database, i didn't use it before. I just prefer to save it to the namespace table for the other works in the future and manual dataset import tasks.

**Comment by clausnagel** [comment]
Thanks, @muratkendir. The CityGML 3.0 Conceptual Model doesn't use any GML classes or concepts. If we understand the 3DCityDB v5 as implementation of the Conceptual Model, then I would like to avoid using the GML namespace. Solids and MultiSurfaces are stored in `geometry_data` and type information goes to the `type` and `geometry_properties` columns. The latter is JSON-based metadata (see [here](https://github.com/3dcitydb/3dcitydb/tree/v5-devel/resources/json-schema/geometryProperties)), so no need for the the GML namespace here either.

The Core module declares a dependency on xAL 3.0. However, the `Address` feature itself is defined in the Core module and, thus, should receive the Core namespace. Address details are stored in the `Address` table.  If we want to additionally keep the original xAL XML snippet, it should go into `val_content` of the `property` table. So, I don't see a requirement to store individual XML elements like `PostBoxNumber`, `PostalCodeNumber`, etc. Also note that these types are xAL 2.0 but not xAL 3.0. So, in summary, we can add the xAL 3.0 namespace but I don't see an urgent requirement for it.

I neither see a use case for the XLink namespace.

**Comment by muratkendir** [comment]
Ok, i understood. We (me and Thomas) have decided to keep "datatype" column in property table at an offline discussion. For Exp. datatypes for "core:lod2Solid" and "core:lod2MultiSurface" should be stored as "gml:Solid" or "gml:MultiSurface". Meanwhile, "core" would be enough to refer to namespace table. I prefer to keep them in both of geometry_data and property tables. 

Similarly, core:name, core:description will be saved with gml:name and gml:description datatypes in the upgrade scripts.

I think that we don't need to save address information in val_content column, since most of address data in CityDBv4 were parsed into those columns (PostBoxNumber, PostalCodeNumber etc.). It sounds me like "re-aggregate a data which is already parsed before". We can store them as complex data just like the con:Height datatype and it's child properties such as HighReference, LowReference etc. If you would prefer to save in a raw format into val_content column, it is ok for me. 

By the way, i don't understand why we need to avoid to use additional namespaces, while the usage purpose of the namespaces is providing uniqueness for the names. "Namespaces are one honking great idea --lets do more of those!". It is a quotation from "Zen of Python" guiding principles list and i guess we can discuss it later in more abstract way, because i think that it would be beneficial to derive different types from inherited resources (For Exp. HeightStatusValue is an enumeration derived from INSPIRE, but is an implicit information and people might not know how to populate those enumerations, code lists etc. )

**Comment by clausnagel** [comment]
> We (me and Thomas) have decided to keep "datatype" column in property table at an offline discussion. 

Something we need to decide in the group.

Address: We already agreed that we don't want to store PostBoxNumber, PostalCodeNumber, etc. as additional rows in the property table. Address information should go into the address table. val_content is optional not mandatory. And yes, you can already store the xAL blob in 3DCityDBv4 is you want.

Namespaces: I am not against namespaces, but I don't see a value in using encoding-specific ones.

**Comment by thomashkolbe** [comment]
>     We (me and Thomas) have decided to keep "datatype" column in
>     property table at an offline discussion.
>
> Something we need to decide in the group.
>

This is only referring to our work at TUM while Murat is working
on the upsert scripts. I am not feeling comfortable with
dropping the datatype column, because I believe it
would be useful for users who connect to the database
not via the import/export tool. Since we are already providing
and filling that column for now, it is easier to keep it for
the moment and to possibly drop it later than to recognize
later that it is useful and to have to re-implement this again.

**Comment by yaozhihang** [comment]
According to the offline discussion on 10.03.23, we decided to define the 3DCityDB-specific namespaces based on the CityGML conceptual model. see https://github.com/3dcitydb/3dcitydb/issues/188. So, close this ticket.
