### ISSUE TITLE
Introduce a new metadata table "DataType"

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#186]
Currently, the meta-information (name, namespace, inheritance hierarchy etc.) of `Object` and `Feature` classes are stored in the `objectclass` table. For applications like Importer/Exporter, the meta-information of the classes like complex data type and union, whose meta-information are also required, but missing in the database. 

The proposal is to introduce a new table `complex_data_type_class` (or complex_data_type), which may have the similar structure like the `objectclass` table. In addition, a new integer column `complex_type_id` should be added to the `property` table. This new column is a FK referencing to the `id` column of the new table. 

We have to implement the proposal as soon as possible, since this is actually a bugfix of the database schema and also a show-stopper for the importer/exporter implementation.

**Comment by thomashkolbe** [comment]
This could be avoided, if we would keep the `datatype` column in the property table as proposed originally. It was exactly the purpose to use this value and then be able to retrieve the data structure from the CityGML data model (or the CityGML XML schema).

However, I agree that it would be inefficient to store the string value of the namespace + datatype repetitively for each single object property. Therefore, we could introduce a new table to represent all datatypes (not only the complex ones), where we list all datatypes including their namespace once, and then we only store a foreign key with each single property in the `property` table. This would allow users to fully understand each property of every stored feature from just working with the database and to create a generic object browser tool in the future.

**Comment by yaozhihang** [comment]
Done with [498df04](https://github.com/3dcitydb/3dcitydb/commit/498df0434cf7e7e4707920b03e9998a3efe02591)
