### ISSUE TITLE
Indexes on n:m tables

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb#19]
Currently, we add an index on each foreign key column in a link table. Both columns also represent the primary key, which is also an index. This index is sorted by the first column in the index. Thus another index on the first column of the primary key is useless. We might only need an index for the second column. In some cases the DB would choose to use an index only scan on the PK index anyway.

I've analysed some queries under Postgres and could see that it uses an bitmap index scan on the PK index if I drop the redundant index. On my machine it was slightly slower than the index scan. Still, one index less to maintain is preferable, especially when you think of write operations such as inserts or deletes.

**Comment by clausnagel** [comment]
Closing since this has not been an issue in practice so far.
