### ISSUE TITLE
Documenation and Website still on version 4

### ISSUE THREAD

**Issue by sehHeiden** [3dcitydb/3dcitydb#195]
The project websites still links to a download file for version 4, which does not work with a current docker container for the database.

In addition the Documentationstill seams to be on version 4.3 The link to lastest, or other versions are brocken.

**Comment by thomashkolbe** [comment]
I guess you mean the website www.3dcitydb.org (or www.3dcitydb.net)? In this case, you are right, we need (and will) update the webpage ASAP. However, I recommend to refer to the github repository for the latest versions of the code and the documentation. (This will be added also as a recommendation to the website)

If you are referring to something else, please clarify.

**Comment by sehHeiden** [comment]
I am refering to www.3dcitydb.org and [readthedocs](https://3dcitydb-docs.readthedocs.io/en/release-v4.2.3/index.html)
