### ISSUE TITLE
type column in geometry_table

### ISSUE THREAD

**Issue by muratkendir** [3dcitydb/3dcitydb#196]
In the table "geometry_data" we have a new integer column named "type". I have a few questions about this column:
- How will this column be populated?
- Will it be GML specific, PostGIS specific, or specific to any file?
- If we are planning to create a PostGIS specific geometry type column, then I need to ask two more questions:
-- Can't we remove this column and just add an index using st_geometrytype()? (if query performance expected)
-- Which geometry standard will it support? "Simple Features 1.1" or "Simple Features 1.2"  (includes new geometry types such as Polyhedral Surface)?

Just a reminder: OracleDB SDO_GTYPE class fits very well for this purpose, but I'm not sure if it covers all geometry types in PostGIS.

**Comment by clausnagel** [comment]
Current values for the type column:

POINT = 1
MULTI_POINT = 2
LINE_STRING = 3
MULTI_LINE_STRING = 4
POLYGON = 5
COMPOSITE_SURFACE = 6
TRIANGULATED_SURFACE = 7
MULTI_SURFACE  8
SOLID = 9
COMPOSITE_SOLID = 10
MULTI_SOLID = 11

The values are 3DCityDB specific, so neither GML nor PostGIS, Oracle, SF. The values are based on the surface geometry types supported in v4 plus new values for points and curves.

The idea was to have an identifier that is _independent_ of the underlying database implementation. So the type column will store the same values if you run the 3DCityDB on PostGIS,  Oracle or maybe more databases in the future. And at least the PostGIS types are less expressive anyway.

The type value is also available from the JSON metadata in geometry_properties, so it could also be queried from there. We nevertheless thought having the additional column might be useful, for example, in case an import tool does not populate the JSON metadata.

**Comment by clausnagel** [comment]
The list of geometry types will not be extensible in contrast to, for instance, `datatype`, `namespace`, and `objectclass` (due to ADEs). So we could have an additional table but I don't think it's really required. I rather think it's sufficient to just have the above list of geometry types in the documentation.

**Comment by thomashkolbe** [comment]
I agree, it would be sufficient (and necessary) to explain that in the documentation. And it would also be recommended to include it as a comment in the create table scripts.

**Comment by muratkendir** [comment]
Ok then, i will add this geometry_type enumeration to the comments of the geometry_data table.
