### ISSUE TITLE
Remove non-selective indexes on objectclass_id columns

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb#20]
Another index issue I found. Courrently, we define an index on each foreign key column. While this makes sense in general, I think it is not so useful on the objectclass_id columns. The variety of different values in these columns is usually very low, think of building installations or traffic areas. Even in thematic surface often store only three different ids for grounds, walls and roofs. I think, we can agree that such indexes are not really useful for filtering. It could be that seq scans would be faster instead, although I haven't analyzed it thoroughly.

The only place where it I would keep an index on objectclass_id is in the cityobject table. But it would also be interesting to compare performance with or without an index ;) If somebody would start to generate many different ADEs in the 3DCityDB, at some point an index might become necessary again for some tables. But, I would leave this up to the user. He could use existing monitoring tools that provide hints for missing indexes.

**Comment by clausnagel** [comment]
Closing since this has not been an issue in practice so far. Users can manually adapt FK indexes if needed.
