### ISSUE TITLE
[Question] CityGML coordinates understanding problem 

### ISSUE THREAD

**Issue by triin1111** [3dcitydb/3dcitydb#200]
Hi!
I have a problem, if anyone is maybe able to help. I have imported data from CityGML into PostGre database. In this data, the wall textures of buildings are isometric, but I need to make them straight. I can translate them from <app:textureCoordinates ring> to actual wall coordinates, but for that I need to know the starting coordinate of <app:textureCoordinates ring>, which coordinate index corresponds to lower left corner of the wall.
Is there information about that in the CityGML database or should I determine it myself somehow?

Thank you so much for help!

**Comment by clausnagel** [comment]
Not sure that I get your issue and what you want to do.

Anyway, the rule in CityGML is simple and as follows: the first texture coordinate in `<app:textureCoordinates>` is applied to the first  coordinate in the referenced linear ring. The second texture coordinate is applied to the second ring coordinate. And so on.

The 3DCityDB does not change anything here but just imports the data as is. If you want to change the assignment of texture coordinates to ring coordinates, then you have to implement this on your own. Same is true if you want to detect the "lower left corner" of your wall surface.

**Comment by clausnagel** [comment]
Closing since this issue is not 3DCityDB related.
