### ISSUE TITLE
Remove column supertype_id of table datatype

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#204]
It is `null` for all datatypes currently. What was the purpose of this column?

**Comment by thomashkolbe** [comment]
I think we have introduced this to have the possibility to represent subclassing for data types. We currently might not have data types in CityGML 3.0 that are derived from other data types, but this could happen in ADEs.

**Comment by clausnagel** [comment]
Ok, in this case the foreign key constraint on `supertype_id` is incorrect:

```sql
CONSTRAINT datatype_supertype_fk FOREIGN KEY (supertype_id)
  REFERENCES citydb.objectclass (id) MATCH SIMPLE
  ON UPDATE CASCADE
  ON DELETE NO ACTION
```

The foreign key is currently defined to reference `objectclass` but shall rather reference `datatype` itself.
