### ISSUE TITLE
Export of 2D building geometries (groundfloor, upperfloor, roofs) as geojson? 

### ISSUE THREAD

**Issue by andredaa** [3dcitydb/3dcitydb#205]
Hello :)
I am looking for a possibility to extract 2D geometries of the buildings. For example all groundfloor geometries as geojson, with the geometrie's height set as a property. 
Is this possible for example using the ST_AsGeoJSON command ?
Does anyone know of an open-source import/export plugin for this purpose?
Best Regards
Andre

**Comment by BWibo** [comment]
Hey, the 3DCityDB Importer/Exporter supports CityJSON too.
https://github.com/3dcitydb/importer-exporter

You can use e.g. an SQL Filter to extract GroundSurfaces:
https://3dcitydb-docs.readthedocs.io/en/latest/impexp/export-filters/sql.html

**Comment by karinpatenge** [comment]
For Oracle Spatial you can use SDO_UTIL.GET_2D_FOOTPRINT in combination with SDO_UTIL.TO_GEOJSON.

**Comment by andredaa** [comment]
Thank you for your feedback :) 
@karinpatenge  We are looking for an open source solution, so unfortunately I think the Oracle solution we could not use. 
@BWibo Can the SQL filter also filter geometries? I am used to working with geojson - however never much touched CityGML. Is there a way to tell which geometry is a footprint/floor one? Are they usually annotated as 1 continuous polygon for a building - or is it many neighboring geometries per floor?

Thank you for your help,
Best
Andre

**Comment by gioagu** [comment]
Dear all,

Maybe not really a solution, but a suggestion to solve the problem from another angle...

Have you considered using the 3DCityDB-Tools plugin for QGIS?
It will allow you to interact with data in the 3DCityDB and create "sort of" traditional GIS  layers (including lod0 footprints and roofprints). From QGIS, you could then generate GeoJSON using the usual export as...

Beware, layers are generated directly in PostgreSQL, so you could use Python (or whatever you prefer) to convert the layers into GeoJSON from there.

Link: https://github.com/tudelft3d/3DCityDB-Tools-for-QGIS

(Check the user manual) ;-)

**Comment by BWibo** [comment]
> Can the SQL export filter also filter geometries?

If you have LoD2 data, you can filter for `BuildingGroundSurfaces` using SQL. Check the Building module of 3DCityDB and look for the `ThematicSurfaces`. UsingPostGIS functions you can for this to 2D.
https://3dcitydb-docs.readthedocs.io/en/latest/3dcitydb/schema/building.html

For LoD1 data this should be possible using PostGIS functions.

**Comment by andredaa** [comment]
@gioagu @BWibo  thank you a lot, both of you. I think I can go from there :)
