### ISSUE TITLE
Drop "val_implicitgeom_transform" column

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#208]
The column "val_implicitgeom_transform" of the "property" table is used to store the transformation matrix of an implicit geometry instance. The transformation matrix is defined as list of 16 doubles (4x4 matrix stored in row-major order). However, we currently store this double list as string with a single space as delimiter. After having introduced "val_array" for storing lists of primitives, this is inconsistent and feels wrong. We also use "val_array" for other double lists such as "storeyHeightsAboveGround" of buildings. We therefore should drop "val_implicitgeom_transform" and use "val_array" instead. There is no information loss in doing so.

**Comment by yaozhihang** [comment]
done with da6901f6
