### ISSUE TITLE
Change gt_orientation to json

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#209]
"gt_orientation" of "surface_data" stores a 2x2 transformation matrix. Currently, the matrix is mapped to a string using a space as delimiter. To be consistent with all other representations of transformation matrices ("world_to_texture_mapping" and #208), the data type of the column should be changed from `text` to `json` to store the matrix as double array.

**Comment by yaozhihang** [comment]
done with ceff3e68
