### ISSUE TITLE
Automatic creation of DELETE scripts with PL/SQL

### ISSUE THREAD

**Issue by FxKu** [3dcitydb/3dcitydb#21]
As the next major release of the 3DCityDB will allow for dynamically adding CityGML ADEs around the core schema, we need a way to create DELETE scripts in a generic fashion. A first version has been developed in january 2018 and is currently tested. It relies greatly on database constraints, such as NOT NULL and foreign keys. The ON DELETE configuration of a foreign key determines the code of a delete script, which is:

delete_A(id):
[A]---<[B:NO ACTION] = delete referencing entries in table B first
[A]---<[B:SET NULL] = do nothing
[A]---<[B:CASCADE] = do nothing
[A:NO ACTION & FK!=PK]>---[B] = do nothing
[A:NO ACTION & FK=PK]>---[B] = call delete_B(id)
[A:SET NULL]>---[B] = cleanup unreferenced entries in table B
[A:CASCADE]>---[B] = do nothing

In order to work also for ADEs extensions the constraints need to be set correctly (should be another ticket). So far, the delete script generator has only been tested against the core schema. There are still some issues.

**Comment by yaozhihang** [comment]
Nice summary! One question: in the case [A:CASCADE & FK=PK]>---[B], we just need to call the delete_B(id) such that the respective row in table A can be automatically deleted using the CASCADE. Is this right?

**Comment by FxKu** [comment]
Ah, good hint. For the fifth case the ON DELETE setting should not matter. If somebody wants to create a delete function for such a table with CASCADE setting on the FK=PK (e.g. masspoint_relief) delete_B must be called in the end. I'll fix that. Of course, calling only delete_B would also be sufficient, but the script generator is not able to handle this scenario at the moment.

**Comment by FxKu** [comment]
The PL/SQL implementation can be found in the `CITYDB_PKG` folder under `DELETE` > `DELETE_SCRIPT_GENERATOR.sql` in the `dev` branch. I've put the resulting functions together to a script and moved it into the `SCHEMA` folder. As we decided to let the ADE Manager Plugin generate the scripts, I think I can close this issue.
