### ISSUE TITLE
Data creation learning-curve barrier

### ISSUE THREAD

**Issue by paulterinho** [3dcitydb/3dcitydb#212]
Firstly, huge thanks for keeping this project open-source. It looks amazing!

Secondly, my team and I are running into a steep learning-curve barrier and were wondering if there were recipes for marshalling data into the cityDB schemas for completely new cities from existing data (OSM, etc...). All existing tutorials either point me to 1) download pre-marshalled GML data (does not edify on how to create new data) from cities that have been in development for 10+ years like Munich, Singapore, or Berlin, or 2) input data by hand. There doesn't seem to be guidance for setting up a completely new city in a semi-automated way to get city-wide baseline data.

I'm trying to get my research team to adopt cityDB but they are pushing back with the fact that, although there are hand-wavy guides (e.g. "just look at the schema and figure it out") there does not seem to be any step by step instructions for semi-automated baseline data creation (like OSM, R5R, or GTFS / GTFS-Pathways in R or Python), for this which is a red-flag for adoption.

Any guidance would be greatly appreciated if possible!

**Comment by clausnagel** [comment]
The 3DCityDB is intended for the storage and management of 3D city models in a database. It's not a tool for the production of 3D data.  Our guides and tutorials therefore assume that users already have their 3D data available (preferably in CityGML or CityJSON format). We have a very detailed [online documentation](https://3dcitydb-docs.readthedocs.io/en/version-2023.0/) of the 3DCityDB relational schema and our open-source tools for loading and extracting data. However, a general guide on how to create 3D city models from arbitrary input data is beyond the scope of this project.

I understand that creating 3D city models can be a challenge at first. There is both commercial and open-source software available for the (semi-)automated creation of 3D models from raw GIS data or for converting existing 2D/3D datasets. And there is a great deal of research on this topic.

I recommend starting with the creation of CityGML/CityJSON files. We can then support you with questions about storing your data in 3DCityDB.

**Comment by paulterinho** [comment]
Hi @clausnagel , I understand, but perhaps this perspective is short-sighted? It poses as a circular barrier in that only people that already know about it can use and contribute to it. 

Without basic guidance my teammates will see this as a risk, ignore this project, and adopt another approach. Moreover, I'm guessing we are not the first outsiders to look at this absolutely amazing project, puzzle over how to get started, and then walk away because there isn't a clear path for entry. 

I did previously find the [online documentation](https://3dcitydb-docs.readthedocs.io/en/version-2023.0/), but sadly it tells me everything _but_ how to get started.  I even logged an issue there hoping for guidance. [Link to the issue](https://github.com/3dcitydb/3dcitydb-docs/issues/47). 

Thank you for the clarification. I'll look around online a while longer online, but I'm really not finding any good info. If ever a section gets added, or someone else may know of a guide for beginners, I would love to hear more about it. It is an excellent looking project.

**Comment by paulterinho** [comment]
Hi @clausnagel 

Apparently it is me that was short-sighted. Your suggestion about looking into CityGML/CityJSON as a starting point was very helpful, thank you!  was not understanding that the different city-forms were like avatars of the same concept. 

Going to close this issue (and the other one too).
