### ISSUE TITLE
Some changes to indexes

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#213]
1. The following indexes are created by default but are not important for 99% of the typical queries. So, they slow down import processes for no good reason. Users can easily add them later if really required.
    - address(objectid)
    - address(identifier, identifier_codespace)
    - address(multi_point)
    - appearance(objectid)
    - appearance(identifier, identifier_codespace)
    - appearance(theme)
    - geometry_data(objectid)
    - implicit_geometry(reference_to_library)
    - property(val_implicitgeom_refpoint)
    - surface_data(identifier, identifier_codespace)
    - surface_data(objectid)
    - surface_data(gt_reference_point)

2. On the other hand, the following indexes are missing although they are important:
    - feature(creation_date)
    - feature(termination_date)
    - feature(valid_from)
    - feature(valid_to)

3. I found inconsistencies with index names. All index names should be checked again. For example:
    - implicit_geometry(objectid) is called `implicit_geometry_inx`. The column name "objectid" is missing. 
    - codelist_entry(codelist_id) is called `codelist_entry_codelist_idx`. The name uses "idx" as suffix. However, for foreign keys we always use "fkx" instead.

**Comment by yaozhihang** [comment]
done with 914a778c
