### ISSUE TITLE
Minor changes to "property" table

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#215]
* Drop `root_id` column
This column makes it easy to query all rows belonging to the same property hierarchy. The same can be achieved using an hierarchical query on `parent_id` though. Dropping this column would also remove the corresponding FK constraint and index both of which are expensive during imports.

* Drop FK constraint on "datatype_id"
This constraint is expensive during imports. Removing it would allow storing values not defined in the "datatype" table. However, such invalid values can simply be ignored in exports and queries.

* Drop FK constraint on "namespace_id"
This constraint is expensive during imports. Removing it would allow storing values not defined in the "namespace" table. However, such invalid values can simply be ignored in exports and queries. The index on "namespace_id" must be kept though.

**Comment by clausnagel** [comment]
* To be consistent, also drop the FK constraint on the "objectclass_id" column of the "feature" table. The index on "objectclass_id" must be kept though.

**Comment by yaozhihang** [comment]
done with a1384f43
