### ISSUE TITLE
Harmonize file names and directory names

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#221]
We currently use a mixture of different schemes for file names and directories. For example

* `Lowercase with minus sign`: like in "3dcitydb", "postgresql", "json-schema", ...
* `Camel case with first character uppercase`: like in "DbSchema", "SQLScripts", ...
* `Camel case with first character lowercase`: like in "geometryProperties,schema.json", ...
* `Uppercase with underscore`: like in "CITYDB_PKG", "CREATE_DB.sql", ...

I think using one scheme consistently would be nice.

**Comment by BWibo** [comment]
I agree. This will require some small changes in the `Dockerfiles` and workflow files.

**Comment by BWibo** [comment]
I would go for `lowercase with minus sign` or `camel case with first character lowercase`, but that's just a personal preference.
