### ISSUE TITLE
Clamp to ground on STK World Terrain

### ISSUE THREAD

**Issue by Abelon38** [3dcitydb/3dcitydb#24]
Hi!

Thanks for a great software! I wonder how can I do to make the exported objects from the 3dcityDB to clamp to ground. I am using 3dcity web map and objects från det 3dcityDB get on the ground on the flat terrain, but as soon as I switsh to STK world Terrain, then my city-objects wont follow the elevations. 

I am guessing that this is customisable on Importer/exporter application?

Thanks for your time!

Regards,
Abel

**Comment by FxKu** [comment]
This belongs into the importer/exporter or web map repo, doesn't it?
But, I know that there is a height setting 'clamp to ground' inthe preferences of the KML/COLLADA/gltf Exporter.

**Comment by Abelon38** [comment]
Thanks for your reply!
I have tried to change configuration on 3DcityDB but doesn't work at all
but i can see that on Google Earth the buildings do clamps on the ground. I
thing this may be an issue in 3dcity web mab.

Regards, Abel

Den 16 feb. 2018 21:19 skrev "Felix Kunde" <notifications@github.com>:
