### ISSUE TITLE
Error in upgrade script to v. 4.4.1

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb#241]
In version 4.4.1 of the 3DCityDB, there is a tiny bug in the UPGRADE.sql script at line 40.

`\set NEW_REVISION 0`

should be instead

`\set NEW_REVISION 1`

in order to automatically upgrade from 4.4.0 to 4.4.1. 
Once you manually edit and change the value, the upgrade script will work as intended.

Best regards,

GA

**Comment by clausnagel** [comment]
Thanks for spotting this, @gioagu. Argh, nasty little bug. I will fix it and update the release packages soon-ish.

**Comment by clausnagel** [comment]
The release packages both in this repo and in `3dcitydb-suite` have been updated. Thanks again for reporting.
