### ISSUE TITLE
`v5` Docker image naming and repo

### ISSUE THREAD

**Issue by BWibo** [3dcitydb/3dcitydb#243]
There are two options:

- We keep the 3DCityDB `v5` images in a separate Docker repo, as we do now
  - `v4`: `3dcitydb/3dcitydb-pg`
  - `v5`: `3dcitydb/3dcitydb-pg-v5`
- Release to `3dcitydb/3dcitydb-pg` and remove `3dcitydb/3dcitydb-pg-v5`, when the first stable release of `v5` is published.

@clausnagel @yaozhihang What do you think? Are the any reasons to separate the two versions?

### Todos

- [ ] Adapt Docker code block in documentation

**Comment by clausnagel** [comment]
Good question. My initial thought was to go for option 2 once we are stable.

**Comment by BWibo** [comment]
Yes, that's what I had in mind too.

**Comment by thomashkolbe** [comment]
Hi, I am not sure whether this is a good idea, because people will use also for some time in the future the 3DCityDB V4 and we might likely still provide some bug fixes for this. How can you then clearly separate between the two major versions? I would like to avoid that users are easily confusing the docker images...

**Comment by BWibo** [comment]
I agree. Most people will use the `latest` tag of the images, which would then point to `v5.x.x` for `3dcitydb`. Then somebody will want to use the latest version of `importer-exporter` image and run into compatibility problems.

@clausnagel Is there a warning e.g. in Importer/Exporter for that case? I recall the Importer/Exporter is doing a check for that. If the user is informed about compatibility in the application, I think it would be OK to just have one repo, which would be easier to maintain. We could also add this to the `v4` docs.

Future bugfixes for `v4` would no be a problem. We just release them as `v4.x.x`.

**Comment by BWibo** [comment]
Closing, we will release the `v5` images in the exisitng repo and delete the `v5` registries after final release.
