### ISSUE TITLE
generic attributes datatype

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/3dcitydb#30]
Hi,

this is not a bug, but rather an idea/suggestion for future releases.

Currently, the datatype of a generic attribute is set 1 to 10 (string, double, integer, etc.).
I feel that this might be replaced by analogous (to-be-added) entries in the objectclass table and get a corresponding column objectclass_id referencing it.
This would make the design and the logic of the table more similar to the other ones in the 3DCityDB.

Just an idea...

**Comment by FxKu** [comment]
Thanks for your question. It's good that we - developers and users - keep thinking about how we could improve the datamodel of the 3DCityDB :)

In this case I wonder if there is any real benefit in changing it? Besides, I think the `objectclass` table isn't really the right place to register feature properties. It's only meant for feature types. If we add a lookup table for properties or maybe only for generic attributes we need to adjust the Importer/Exporter tool and the SQL setup scripts. In the 3DCityDB we also allow for storing generic attributes with datatypes that are not supported in the standard (geomval, blobval). This would require a special treatment as well (would we store them in the lookup table or not?) etc. You see, quite some effort for gaining what exactly?

Another aspect is also stability of the schema. The tables havn't really changed in the last 10 years. Sometime I have argued with other contributers that it is about time to change some parts of the schema, but most often I had to admit that stability is a stronger argument. For users and also companys who rely on this project.
