### ISSUE TITLE
How to import/export citygml ADE data?

### ISSUE THREAD

**Issue by YinChaoOnline** [3dcitydb/3dcitydb#33]
Hi? I have developed a CityGML ADE for Cadastre(UML and XSD). I am look for help to figure out the roadmap for importing and exporting the Cadastre-ADE examples data into 3d city db.

I have searched the web, but seemly there is no evident infomation about integrating CityGML ADEs into 3d city db?

My superficial roadmap is:
- ADE(XSD, UML, some examples data)
- develop cadastre-ade module for citygml4j just like noise-ade
- let importer-exporter based on the newly devleoped citygml4j
- ？develop postgresql db schemas?( I am not sure for this step)

Can someone point out a reasonable way to accomplish my goal storing/exporting the ade data in postgresql?

**Comment by FxKu** [comment]
Closing as redundant to [(https://github.com/3dcitydb/importer-exporter/issues/44)]
