### ISSUE TITLE
Wrong envelope calculated for ReliefFeature

### ISSUE THREAD

**Issue by clausnagel** [3dcitydb/3dcitydb#36]
1. Set up a new 3DCityDB 4.0 instance with `SRID = 25832`
2. Import this dataset: http://schemas.opengis.net/citygml/examples/2.0/building/Building_LOD2-EPSG25832.gml
3. Recreate all BBOXes with `core:_CityObject` as top-level feature
4. Export as CityGML dataset

In the exported CityGML dataset, the BBOX of the ReliefFeature will be as follows, which is wrong:
``` xml
<gml:Envelope srsName="urn:ogc:def:crs:EPSG::25832" srsDimension="3">
  <gml:lowerCorner>458880.0 5438352.6 112.0</gml:lowerCorner>
  <gml:upperCorner>458880.0 5438352.6 112.0</gml:upperCorner>
</gml:Envelope>
```
If you repeat the above steps, but use a feature class filter in step 2 to just import the `ReliefFeature` without the `Building`, then the BBOX will be correctly calculated as follows:

``` xml
<gml:Envelope srsName="urn:ogc:def:crs:EPSG::25832" srsDimension="3">
  <gml:lowerCorner>458868.0 5438343.0 112.0</gml:lowerCorner>
  <gml:upperCorner>458892.0 5438362.0 114.0</gml:upperCorner>
</gml:Envelope>
```

**Comment by yaozhihang** [comment]
Many thanks for the bug report. Fixed in https://github.com/3dcitydb/3dcitydb/commit/0c762eea33b85544c017283a3d9f984d610f8d1f

**Comment by clausnagel** [comment]
:thumbsup:
