### ISSUE TITLE
Slow queries on codespace attributes

### ISSUE THREAD

**Issue by sensor-freak** [3dcitydb/3dcitydb#37]
Querying by codespace attributes is slow. I suggest to add an index to every codespace column (e.g. building.function, building.roof_type, ...). Please note that I mean the actual data column ('function'), not the codespace definition column ('function_codespace').

**Comment by FxKu** [comment]
Well, you're free to create an index on all columns you want to filter on :)

I think, it's better to leave this up to the user. Every index requires disk space and - more important - affects write performance. So, we ship the 3DCityDB only with indexes on foreign key columns and spatial attributes (ok, and gmlid columns), which is a general recommendation for databases. One could argue that even some spatial indexes are not really necessary like the ones for `terrain_intersection_curves`. 

In general, every database user should do some monitoring on his/her own to detect slow queries and create indexes.
