### ISSUE TITLE
How to update database ??

### ISSUE THREAD

**Issue by Navidshamshirband** [3dcitydb/3dcitydb#39]
Hello there,

I created database with the help of the Importer/Exporter for my Citygml data (LOD1 and LOD2).
But the other task of mine is how do we able to update our database e.g. importing new buildings or eliminating some.
Based on my search,I found that it is possible with VirtualcityDATABASE. But the problem is, it is commercial and almost not possible for me to buy and company as well.
Does anyone know if there is any trial or student version?
also has anyone any Idea how do we update without VCD?
Thanks in advance

**Comment by daniel-de** [comment]
Hi,

with version 3.3 we use the delete_cityobject-function to delete buildings
`SELECT citydb_pkg.delete_cityobject(id);`

**Comment by yaozhihang** [comment]
We've recently release a new version of Importer/Exporter which allows to delete cityobjects via CLI.
Download link: https://github.com/3dcitydb/importer-exporter/releases/tag/v4.2.3
Documentation: https://3dcitydb-docs.readthedocs.io/en/release-v4.2.3/impexp/cli.html
