### ISSUE TITLE
Importing textures URI - v2.1 vs 3.0

### ISSUE THREAD

**Issue by ngauthe** [3dcitydb/3dcitydb#4]
Hello,
While running some tests on 3dcitydb I noticed a difference beetween the old (2.1) and new version (3.0) when importing appearances but not texture files
In the older version, under these settings, the texture file URIs were imported in table "surface data" (column "tex_image_uri")
In version 3.0, with the same preferences, the table "tex_image" is empty (URIs are not imported)
Having found no mention of this change in the documentation, I was wondering if it was known/intended

**Comment by clausnagel** [comment]
Thanks for reporting. Actually, we did not change this behaviour by intention. Do you rely on this feature?

**Comment by ngauthe** [comment]
Thanks for the answer. I can't say I am relying on this feature since I'm only in the testing phase of 3dcitydb as a possible technical solution for a project (storage of multiple 3D city models), but this is the settings we'd like to use.

**Comment by clausnagel** [comment]
Readded in v3.1.0.
