### ISSUE TITLE
Error in postgresql migration when database name is not the default "citydb"

### ISSUE THREAD

**Issue by prusswan** [3dcitydb/3dcitydb#40]
<pre>
Upgrading 3DCityDB ...

Checking version of the 3DCityDB instance ...
4.0.1

DO_UPGRADE.sql

Upgrading schema 'citydb_pkg' ...
psql:../../CITYDB_PKG/CONSTRAINT/CONSTRAINT.sql:188: ERROR:  relation "surface_geometry" does not exist
LINE 30:   AND c.confrelid = 'surface_geometry'::regclass::oid
                             ^
Press any key to continue . . .
</pre>

Source: PostgreSQL/SQLScripts/CITYDB_PKG/CONSTRAINT/CONSTRAINT.sql:188

Possible fixes: 

    'citydb.surface_geometry'::regclass::oid
    (lower($2) || '.surface_geometry')::regclass::oid

**Comment by yaozhihang** [comment]
@prusswan many thanks for the bug report. I prefer the second one of your proposed fixes.
I opened a Pull-Request here #41. Please check and test it if all now work with your database environment.

**Comment by prusswan** [comment]
Yup it works now, but maybe rollback is needed in case of errors. Right now manual reset is needed for `citydb_pkg.citydb_version`

**Comment by yaozhihang** [comment]
fixed in release v4.0.3
