### ISSUE TITLE
update 'System Requirements' of 3DCityDB

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#42]
The UPGRADE-script `DO_UPGRADE.sql` currently uses the PostgreSQL's Object Identifer (OID) `regnamespace` which is only supported by PostgreSQL version 9.5 or later.
(https://www.postgresql.org/docs/9.5/datatype-oid.html).
In addition, the `?` function is introduced by PostgreSQL starting from its version 9.6
We have to update the 'System Requirements' of 3DCityDB:
**PostgreSQL DBMS >= 9.6 with PostGIS extension >= 2.3**.
PostGIS 2.3 is encouraged to be used together with PostgreSQL 9.6. see detilas here: https://postgis.net/2016/09/26/postgis-2.3.0/

**Comment by FxKu** [comment]
unnest is there since Postgres [8.4](https://www.postgresql.org/docs/8.4/functions-array.html). But with `regnamespace` you're right. It's usage could easily be avoided instead of updating the system requirements.

**Comment by yaozhihang** [comment]
@FxKu my mistake, thanks.

**Comment by yaozhihang** [comment]
updated in release v4.0.3
