### ISSUE TITLE
Error on Creating Database

### ISSUE THREAD

**Issue by Darkelyzed** [3dcitydb/3dcitydb#44]
So basically, i'm here tryinh the tutorial that given by the 3dcitydb. i'm at the step to create DB. but, i'm stuck at this step because some error that i cannot understand. After i input the reference, i've got this message

`psql:SCHEMA/SCHEMA.sql:1444: ERROR:  type "raster" does not exist
LINE 3:  rasterproperty raster,`

**Comment by zjdcsu** [comment]
I meet a similar problem when after input the reference. How did you solve this?
![image](https://github.com/3dcitydb/3dcitydb/assets/152605145/529d3ffb-295f-487b-af3d-e94af3ec5435)
