### ISSUE TITLE
TINRelief feature is imported but can't be exported

### ISSUE THREAD

**Issue by arruga** [3dcitydb/3dcitydb#46]
I have generated some TINRelief terrain models each one with a polygon extent and an appearance. They are validated as correct and imported by 3dcitydb v4.2.0 without error. I can see that some records in postgres tables (tin_relief, surface_geometry, tex_image, appear_to_surface_data...) have been created, but I have no record in relief_feature table. When I try to export relief features I don't get anything. I also have buildings that export properly. Is that a bug or have I done something very wrong?
I send you attached an example:
[TIN_Alcover_9.zip](https://github.com/3dcitydb/3dcitydb/files/4443285/TIN_Alcover_9.zip)

**Comment by arruga** [comment]
Previous zip file had some unneeded images.
[TIN_Alcover_9.zip](https://github.com/3dcitydb/3dcitydb/files/4443351/TIN_Alcover_9.zip)

**Comment by yaozhihang** [comment]
Hi,

this is due to an issue in the data. The `TinRelief` is not a CityGML top-level feature and hence must be nested by the top-level feature `ReliefFeature`. A good example:

```
  <cityObjectMember> 
    <dem:ReliefFeature gml:id="GML_6bb30328-7599-4500-90ef-766fde6aa67b"> 
      <gml:name>Example TIN LOD0</gml:name> 
      <dem:lod>0</dem:lod> 
      <dem:reliefComponent> 
        <dem:TINRelief gml:id="GUID_04D4DsNGv1MfvYu5O3lkcW"> 
          <gml:name>Ground</gml:name> 
          <dem:lod>0</dem:lod> 
          <dem:tin> 
            <gml:TriangulatedSurface gml:id="ground"> 
              <gml:trianglePatches> 
                <gml:Triangle> 
                  <gml:exterior> 
                    <gml:LinearRing> 
                      <gml:posList>458868 5438362 112 458875 5438355 112 458883 5438362 114 458868 5438362 112 </gml:posList> 
                    </gml:LinearRing> 
                  </gml:exterior> 
                </gml:Triangle> 
                … 
              </gml:trianglePatches> 
            </gml:TriangulatedSurface> 
          </dem:tin> 
        </dem:TINRelief> 
      </dem:reliefComponent> 
    </dem:ReliefFeature> 
  </cityObjectMember> 
```

**Comment by arruga** [comment]
Thank you!
