### ISSUE TITLE
[PostgreSQL] Failed to run the "cleanup_schema" procedure if the citydb schema contains a user-defined view

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#48]
This issue can be raised when the user try to create views for the use of PostgREST with the 3DCityDB Web Map client

**Comment by clausnagel** [comment]
@yaozhihang, does this bug still exist or has it been fixed in the meantime?

**Comment by yaozhihang** [comment]
still an issue in both v4 and v5
