### ISSUE TITLE
Complete city list?

### ISSUE THREAD

**Issue by marzig76** [3dcitydb/3dcitydb#49]
Is there a complete list of cities that are supported in this project?  I tried looking through the documentation and can't seem to find anything.

Thank you.

**Comment by yaozhihang** [comment]
Hi, maybe the following link is what you are looking for?
https://www.3dcitydb.org/3dcitydb/3dcitydb-in-action/

**Comment by marzig76** [comment]
This is a good place to start.. Thanks
