### ISSUE TITLE
Question 3d Citydb

### ISSUE THREAD

**Issue by steffiarg** [3dcitydb/3dcitydb#51]
Hello, we created the database within Postgresql with all the tables, we want to know how to add data to them. We tried with the Importer/Exporter tool, but it throws us the following error "Database error while querying index status. Org.portgresql.util.PSQLException: ERROR: no existe la relacion <citydb.index_table>. Where: funcion pL/pgSQL citydb_pkg.status_spatial_indexes (text) en la linea 5 en EXECUTE."

**Comment by FxKu** [comment]
@steffiarg are you sure you connect to the right database. If you've set up the 3DCityDB correctly the `citydb` schema with `index_table` table should be there. If it's missing, check you Postgres logs why it could not get created. Maybe there's an issue with creating the UDT `citydb_pkg.INDEX_OBJ`?

**Comment by steffiarg** [comment]
Hello, thanks to your answer I noticed that I do not have  tables created in the citydb_pkg scheme, but I have in the citydb scheme. How strange! I will check if I find the error, if not consult. Thank you!

**Comment by steffiarg** [comment]
Do not find the error log. You can send the file that contains the commands that create all the tables I need? or if you can just command to create that table?

**Comment by clausnagel** [comment]
@steffiarg there is an online documentation available at https://3dcitydb-docs.readthedocs.io/en/release-v4.2.3/. I recommend that you follow the installation steps as described there.

**Comment by steffiarg** [comment]
@clausnagel I have followed the steps of that guide and others for the installation. I do not know why it has not been installed correctly.

**Comment by steffiarg** [comment]
Hi, I fixed the problem. I re-created the 3d database, I was missing the raster extension. Thanks
