### ISSUE TITLE
Importer-Exporter v4.2.3 does not support database v4.1.0

### ISSUE THREAD

**Issue by gperonato** [3dcitydb/3dcitydb#56]
The latest release of the Importer/Exporter (4.2.3) cannot connect to a database created with the latest release of the bash scripts, as the version 4.1.0 is not supported.

**Comment by clausnagel** [comment]
Yes, by intention. Note that the 3DCityDB v4.1 **is not released yet**. It be published together with the next version 4.3 of the Importer/Exporter, and then you will be able to connect, of course :-) If you want to have a sneak preview, then build the Importer/Exporter from the `master` branch.

**Comment by gperonato** [comment]
Ok, thank you for the quick reply! So I guess v4.0.3 should be used in production, right?
