### ISSUE TITLE
Add function/tool to cleanup Orphaned tmp_* tables created by the imp-exp

### ISSUE THREAD

**Issue by MattSmillie** [3dcitydb/3dcitydb#57]
It would be great to have a little function that would go through and cleanup any Orphaned tmp_* tables created by the imp-exp.

Sometimes when a connection is interrupted during an export the tables get left behind. Not a huge issue but it would be nice to have a little function. I just checked a database and it has ~50 or so of these tables.

I assume it's fairly easy to remove these tables with some SQL.

**Comment by clausnagel** [comment]
The Importer/Exporter 5.0 has been changed to not commit temporary tables anymore to avoid polluting the 3DCityDB schema with orphaned tmp_* tables (see [change log](https://github.com/3dcitydb/importer-exporter/blob/master/CHANGES.md) and [PR #190](https://github.com/3dcitydb/importer-exporter/pull/190)).
