### ISSUE TITLE
display data from local database to web map

### ISSUE THREAD

**Issue by ahmadzainuririzaldi** [3dcitydb/3dcitydb#62]
I have imported data into postgre using importer/exporter tools.

the next step, I want to display the data that I have imported to the web map

do I have to export my data first manually using the importer/exporter tools?

is there some kind of way to display data in a web map where the data is directly fetched from 3dcityDB(like using the API) ?

**Comment by Son-HNguyen** [comment]
Discussed in https://github.com/3dcitydb/3dcitydb-web-map/issues/65.
