### ISSUE TITLE
id nextval in generic_cityobject

### ISSUE THREAD

**Issue by stirringhalo** [3dcitydb/3dcitydb#7]
Is there a particular reason why the id column in the generic_cityobject table is not nextval incremented?

**Comment by clausnagel** [comment]
Yes. The ```id``` column of ```generic_cityobject``` references the ```id``` column of ```cityobject``` per foreign key constraint. The latter is nextval incremented using the ```cityobject_seq``` sequence.

**Comment by stirringhalo** [comment]
Ok, makes sense!
