### ISSUE TITLE
CLI batch import does stop due to failing creation of workes

### ISSUE THREAD

**Issue by AndreM84** [3dcitydb/3dcitydb#78]
Dear 3dCityDB team,

I created a (not so straight foreward) workflow for mass import of LoD2 CityGML data into the 3DCityDB.

I am performing spatial data analyses in R which was the reason why  I used this language as a starting point and for triggering everything else around GIS data import, preparation and analysis.
The work flow is more or less:

1. Create a CityDB in the Postgres database manually
2. in R scan directories for CityGML data files,
3. in R create a batch file with the impexp commands for the windows command line for the first data directory
4. from R via the command line execute batch file for data import (impexp; see code below)
5. from R via command line (psql) when import is finished exectue several psql commands on the imported data in the CityDB and start certain spatial analyses on the pre-processed data in R
6. when spatial analysis is finished redo steps 3-5 for the next directory

The workflow was successfull already, even with a large amount of .xml-files (>15k) to be imported in a single iteration of step 4 (above). Importing a data set with a lower number of files (~5k) leads now to the error prompt (while my routine is executing step 4)

> [15:11:46 INFO] Cleaning temporary cache.
> [15:11:46 ERROR] Failed to create import worker.
> [15:11:46 ERROR] Caused by: org.postgresql.util.PSQLException: FATAL: tut mir leid, schon zu viele Verbindungen
> [15:11:47 INFO] [db_importer_pool] Adapting pool size to 1 core worker(s) and 6 maximum worker(s).
> [15:11:47 INFO] Importing file: W:\BKG Leipzig\300001068_LoD2\lod2\he\he.zip\LoD2_446_5622_2_HE.xml
> [15:11:47 ERROR] Failed to create import worker.
> [15:11:47 ERROR] Caused by: org.postgresql.util.PSQLException: FATAL: tut mir leid, schon zu viele Verbindungen
> [15:11:47 INFO] [db_importer_pool] Adapting pool size to 1 core worker(s) and 1 maximum worker(s).
> [15:13:35 INFO] Resolving XLink references.
> [15:13:35 ERROR] Failed to create XLink resolver worker.
These error/info messages continue until the importer tool tried to import all files ( which are in one single zip-container) in the directory without success.

I assume that this comes from the restriction of maximum parallel workers in my PostgreSQL config file. However, I was wondering why this can happen. Since this is the second time, I am facing this error I already configured the  max. `worker-threads` parameter in the command line for impexp execution:

`"C:\Users\MYNAME\3DCityDB-Importer-Exporter\bin\impexp.bat" import "W:\BKG Leipzig\300001068_LoD2\lod2\he\he.zip" -T postgresql -H localhost -P 5432 -d "[MYDBNAME]" -S citydb -u [MYUSER] -p [MYPASS] --worker-threads=6`

The max. number of 6 is (i think well) below the configuration of PostgreSQL

> #max_worker_processes = 12		# (change requires restart)
> #max_parallel_maintenance_workers = 4	# taken from max_parallel_workers
> #max_parallel_workers_per_gather = 4	# taken from max_parallel_workers
> #parallel_leader_participation = on
> #max_parallel_workers = 8		# maximum number of max_worker_processes that
> 					# can be used in parallel operations

Since my PostgreSQL is a desktop server with nothing else connecting to PostgreSQL, the only operations at the time of the import is the import routine as describes above.

Is there an easy way to force a "check for free worker capacity and wait if no worker can be created" operation?

Thanks for any hints.
Best regards
André

[P.S.: In the meantime, I will check on what consequences the increase of max. workers in the PpstgreSQL config file will have for the stability of my  PostgreSQL server]

**Comment by clausnagel** [comment]
Can you share the data for testing purposes?

**Comment by AndreM84** [comment]
Dear Claus,
the data fromat is the  as provided by the German Federal Agency for Cartography and Geodesy.
> Sample CityGML LoD2 data from the German Federal Agency for Cartography and Geodesy ([LoD2-DE-utms-citygml.zip](https://sg.geodatenzentrum.de/web_public/gdz/testdaten/LoD2-DE-utms-citygml.zip)).

Unfortunately, the data is not available for public yet and the usage is restricted for the analyses in my PhD/research project.
If you think it is helpful, I can clone the sample buildings (from the link above) to create a dataset which has an equivalent size (no. of buildings and/or no. of xml files).

**Comment by clausnagel** [comment]
@AndreM84, I made several tests with imports including 5k files and more. I cannot reproduce the error. Please post more information about your settings (Importer/Exporter version, 3DCityDB version, PostgreSQL and PostGIS version, ...). And yes, having the same test datasets would help us to identify the problem on your side.

One question related to your process: Are you invoking multiple import operations _in parallel and at the same time_ from your R code?

In general, the PostgreSQL error message:

> Caused by: org.postgresql.util.PSQLException: FATAL: tut mir leid, schon zu viele Verbindungen

means that the limit of concurrent connections of your PostgreSQL database has been reached. The Importer wants to open another connection, but PostgreSQL refuses to do so. This has nothing to do with the `max_worker_*` settings in PostgreSQL. The number of maximum connections is rather controlled by the `max_connections` setting. So, increasing this number might solve your problem.

However, typically the default value is 100 concurrent connections, and the question is, why you are reaching this limit at all. The Importer uses approx. 3 connections per worker thread. Based on your above post, you use 6 worker threads (`--worker-threads=6` parameter of the import command). Thus, you should have something around 18 connections and, thus, far less than 100.

I recommend that you monitor the open connections (sessions) to your PostgreSQL database during the import operation. One easy way to do this is to use pgAdmin and its dashboard view. In my tests, I always had a stable number of 12 open connections independent of the number of files I imported.

**Comment by AndreM84** [comment]
Dear @clausnagel,
thank you for the additional details on the difference of  `max_worker*` vs. `max_connections`. I was not aware, that the `max_worker*` error message was related to the inability to establish a new connection.
I checked the psql-config file and, in deed, the `max_connections` are set to 20. 

I think I remember that I changed that on a basis of any _increase the performance of your PostgreSQL database_ tutorial to allow few operations with high memory demand, but to avoid situations, where to many connections are demanding the relatively high memory.

I set back the default value (100) for  `max_connections` now and will check the import routine again. I am optimistic, that it will work fine now.

Regarding your question 
> One question related to your process: Are you invoking multiple import operations in parallel and at the same time from your R code?

The R script opens two DBI-connections to the PostgreSQL DB which are left opened all the time. The impexp is called via CMD sequentially and no other R code is executed in the meantime. However, pgAdmin4 in most cases is opened as well to have a low level monitoring on the PostgreSQl server/db activities and from time to time QGIS was connected to the PostgreSQL DB as well. So, the max. of 20 connections could be reached I think.

I will give you another feedback (and hopefully close the issue) as soon as the import is running well.

Many thanks and best regards
André

**Comment by clausnagel** [comment]
Thanks @AndreM84, looking forward to your feedback.

You can reduce the number of connections by reducing the number of import workers. For example, use `--worker-threads=2` on the command-line when invoking the Importer/Exporter instead (you shouldn't use fewer than 2 worker threads though).

**Comment by AndreM84** [comment]
Thanks @clausnagel for your help.
I had to adjust some codes of line due to other resaons, but the automated citygml data import using `IMPEXP` import via R and CMD works fine now.
