### ISSUE TITLE
Unable to open the file CONNECTION_DETAILS on windows

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/3dcitydb#80]
Hi,

I double-clicked the CONNECTION_DETAILS.bat file under 3dcitydb/postgresql/ShellScripts, there is no reaction. I also could not open it with text editor. Could you please tell me how to open it? Thank you.

**Comment by yaozhihang** [comment]
Notepad++ is good tool for opening and editing the  CONNECTION_DETAILS.bat file

**Comment by Ferkelcode** [comment]
Thank you, it works.
