### ISSUE TITLE
SRID for CREATE_DB.bat

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/3dcitydb#81]
Hello,

I excute the CREATE_DB script, and the SRID is required. 
 
In the turorial, it says:

First, specify the SRID to be used for the geometry columns of the database. Unlike previous version of the 3D City Database there is no default CRS defined.
Second, specify the SRID of the height system if no true 3D CRS is used for the data. This can be regarded as metadata and has no effect on the geometry columns in the database. The default value is 0 – which means “not set”.
Third, provide the GML compliant uniform resource name (URN) encoding of the CRS. The default value uses the OGC namespace and comprises of the first two user inputs: urn:ogc:def:crs,crs:EPSG::<crs1>[,crs:EPSG::<crs2>].

But I connot find the SRID under Public - Columns - srid, where can I find the srid?

Thank you.

**Comment by BWibo** [comment]
The SRID is usually derived from the dataset you want to import. The 3DCityDB needs to match the spatial reference system of your dataset.
Check the first lines of your citygml file for `srsName='...'. This will allow you to derive the SRID:
![grafik](https://user-images.githubusercontent.com/7643434/162171218-127ea8a6-586f-473a-9d2b-f990887769da.png)

In some cases a website like this can be helpful too:
https://epsg.io/
