### ISSUE TITLE
(CREATE_DB) Is the server running on that host and accepting TCP/IP connections?

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/3dcitydb#83]
Hello, 

I excuted CREATE_DB, and provided SRID, EPSG code, and srsName. It tried to connet to the database, but error shows: 

> psql: error: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
>         Is the server running on that host and accepting TCP/IP connections?
> connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
>         Is the server running on that host and accepting TCP/IP connections?

What is the problem?

**Comment by BWibo** [comment]
Hey there, this error has nothing to do with the 3DCityDB, it is a PostgreSQL connection problem.
Do what the error message says: Check if you server is running and accepting connections.

These two links are a good starting point to analyze and resolve typical postgres connection issues:

* https://stackoverflow.com/questions/20825734/postgresql-connection-refused-check-that-the-hostname-and-port-are-correct-an
* https://bobcares.com/blog/postgressql-connection-refused/

Closing. Feel free to reopen if you can't manage to resolve this. In that case we will need much more detailed information on your setup.

**Comment by Ferkelcode** [comment]
Thank you very much, I reinstall with the postgre server and it works not. But in the next step I was asked to provide password, however I am not able to type in. Do you know why?
