### ISSUE TITLE
function postgis_lib_version() does not exist

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/3dcitydb#85]
When excuting the CREATE_DB.bat, after connecting to the DB, it shows:

> psql:CREATE_DB.sql:36: ERROR:  function postgis_lib_version() does not exist
> ZEILE 1: SELECT postgis_lib_version() AS postgis_version;
>                 ^
> TIP:  No function matches the given name and argument types. You might need to add explicit type casts.

Do you know how to solve the problem? Thank you.

**Comment by clausnagel** [comment]
@Ferkelcode, please follow the installation steps as documented in our online user manual: https://3dcitydb-docs.readthedocs.io/en/version-2022.0/first-steps/setup-3dcitydb.html#installation-steps-on-postgresql.

The user manual is really comprehensive. Step 2 at the above URL will already solve your issue.
