### ISSUE TITLE
Upload .xsd file to a new schema

### ISSUE THREAD

**Issue by Ferkelcode** [3dcitydb/3dcitydb#90]
Hello,

I want to uploade a .xsd to add a new schema in my database,  I input the file in the XML Schema file at the top of the ADE transformation dialog, and then push the Read XML Schema button.
Then I do the ADE transformation following https://3dcitydb-docs.readthedocs.io/en/version-2021.1/plugins/ade-manager/ade-transformation.html 

the console shows:

> [09:29:30 INFO] Start parsing ADE XML schema...
> [09:29:31 INFO] Parsing ADE XML schema completed.
> [09:29:40 INFO] Transforming ADE XML schema to relational database schema...

then it just stop at the Transforming ADE XML schema to relational database schema... 
There is also no output in my output folder.
 
What can I do?

Thank you

**Comment by Ferkelcode** [comment]
I have download the energy-ade-2.0.0 and unzip to ade-extensions folder, and try to register as follow:

> Starting the registration process
> 
> Provide the path to the root folder of the ADE extension package in the corresponding input field of the user dialog (see [Fig. 5.19](https://3dcitydb-docs.readthedocs.io/en/version-2021.1/plugins/ade-manager/ade-registration.html#ade-manager-plugin-ade-registration)). You can either enter the folder manually or open a file selection dialog via the Browse button. Afterwards, click the Register ADE button to start the process. If a database connection has not been established manually beforehand, the currently selected entry on the Database tab is used to connect to the 3D City Database. The separate steps of the registration process as well as all errors and warnings that might occur during the registration are reported to the console window.

But the error shows: 


> [08:31:16 INFO] ADE registration started...
> [08:31:16 INFO] Importing ADE metadata into database...
> [08:31:20 ERROR] Failed to register ADE.
> [08:31:20 ERROR] Caused by: org.citydb.plugins.ade_manager.registry.ADERegistrationException: Failed to import ADE metadata into database.
> [08:31:20 ERROR] Caused by: java.sql.SQLException: javax.xml.bind.JAXBException: Failed to open schema mapping resource from file 'C:\Users\m32az\Desktop\3DCityDB-Importer-Exporter\ade-extensions\schema-mapping\schema-mapping.xml'.
> [08:31:20 ERROR] Caused by: javax.xml.bind.JAXBException: Failed to open schema mapping resource from file 'C:\Users\m32az\Desktop\3DCityDB-Importer-Exporter\ade-extensions\schema-mapping\schema-mapping.xml'.


What is the problem?

**Comment by yaozhihang** [comment]
Has your XSD file been derived from a Enterprise Architect UML model automatically? If not, your XSD might not conform to the encoding rules of ISO19136 Annex E and cannot be processed by the ADE manager plugin. Could you share your XSD file?

**Comment by Ferkelcode** [comment]
Thank you, this is my XSD file.
[EnergyADE.zip](https://github.com/3dcitydb/3dcitydb/files/8707156/EnergyADE.zip)

**Comment by yaozhihang** [comment]
Thanks for sharing the XML schema. I used the latest version of the importer/exporter and am able to derive the database schema (79 tables)
Could you do a test again? The importer/exporter can be downloaded here:
https://github.com/3dcitydb/3dcitydb-suite/releases/tag/v2022.0.0

**Comment by Ferkelcode** [comment]
![Screenshot 2022-05-18 125121](https://user-images.githubusercontent.com/77849645/169022567-40d38550-f05e-4c7d-b1e7-f1e123b805a4.png)
Thank you very much for the answer. 
I installed the latest version of the importer/exporter,  but it stays same. Just stopped at the

> [12:50:48 INFO] Transforming ADE XML schema to relational database schema...

I am not sure if I understood the tutorials (https://3dcitydb-docs.readthedocs.io/en/version-2022.0/first-steps/install-impexp.html ) correctly. I first selected the XSD file for the ADE Transformation-XML Schema, and then press CML Schema einlesen, and and I transform. 

If it is successful, I will find output in the output folder, and the I use this file to to the ADE Registration. Is this correct? 

Because I followed the tutorials there was first ADE Registration, but I dont have the ADE Extension files.

But so far my ADE Transformation was not successful.

**Comment by yaozhihang** [comment]
Using the same settings i can still not reproduce the problem. Maybe you could test this on another computer? If you are using java 8, you could also try to install java 11 and test again.

**Comment by Ferkelcode** [comment]
Thank you. I used java 18, after I changed to java 11 it works.

**Comment by clausnagel** [comment]
Yes, it is correct. The Importer/Exporter cannot process ADE data in a generic way. You have to implement an ADE extension for it manually. See also here: https://3dcitydb-docs.readthedocs.io/en/latest/plugins/ade-manager/impexp-ade-extension.html

**Comment by Ferkelcode** [comment]
Thank you.

![image](https://user-images.githubusercontent.com/77849645/169650336-d5ea06a1-ac6a-44ff-842f-25528a246fdb.png)
I followed the guide, but have another situation than the description, I had a cross for Exporter/Importor. Do you know what can I do ?

I also cannot find the feature class:
![image](https://user-images.githubusercontent.com/77849645/169650387-be1408a5-1c86-4fa1-b0e2-493b2d108cca.png)

**Comment by clausnagel** [comment]
You must provide Java libraries for processing your ADE in the `lib` folder. These libraries are _not created automatically_ by the ADE Manager Plugin but you have to implement them yourself. Only if you provide them, you will get a green check in the "Importer/Exporter" column of the ADE table. This is what the [note in chapter 5.3.6](https://3dcitydb-docs.readthedocs.io/en/latest/plugins/ade-manager/impexp-ade-extension.html) of the user manual says.

A general example for implementing an ADE Java library is provided here: https://github.com/3dcitydb/extension-test-ade

Or you can use the ready-to-use Energy ADE extension for the 3DCityDB: https://github.com/3dcitydb/energy-ade-citydb. However, this ADE only implements the "Karlsruhe Institute of Technology (KIT) profile of the Energy ADE version 1.0". But maybe that's sufficient for your purpose.

**Comment by Ferkelcode** [comment]
Thank you.

I have used:
![image](https://user-images.githubusercontent.com/77849645/169653181-ab2f9d06-2260-48e9-9b60-c8c0b357c800.png)
energy-ade-citydb-2.0.0.jar
energy-ade-citygml4j-1.0.4.jar
in the lib folder,
however, the problem stays same.

Are these two not the one you meant:

> Or you can use the ready-to-use Energy ADE extension for the 3DCityDB: https://github.com/3dcitydb/energy-ade-citydb. However, this ADE only implements the "Karlsruhe Institute of Technology (KIT) profile of the Energy ADE version 1.0". But maybe that's sufficient for your purpose.

**Comment by Ferkelcode** [comment]
Thank you.

I have put the 2 file in the lib folder:
energy-ade-citydb-1.2.0.jar
energy-ade-citygml4j-1.0.0.jar 

From EnergyADE v1.2.0
![image](https://user-images.githubusercontent.com/77849645/169654997-7952b675-62c1-4f0c-a5f6-7a67891c245b.png)
 But it still doesn't work

**Comment by clausnagel** [comment]
Ok, I tested the following steps to make sure they work.

1. Download the 3DCityDB Suite boundle v2022.0 from [here](https://github.com/3dcitydb/3dcitydb-suite/releases/tag/v2022.0.0).
2. Run the JAR file to install the Importer/Exporter following this [guide](https://3dcitydb-docs.readthedocs.io/en/version-2022.0/first-steps/install-impexp.html).
    - Make sure to choose the ADE Manager Plugin for installation (it is selected by default).
3. Install a new 3DCityDB instance on your PostgreSQL database. Use the database scripts in the `3dcitydb` folder that is located inside the installation directory of your Importer/Exporter (see step 2). Follow this [step-by-step guide](https://3dcitydb-docs.readthedocs.io/en/version-2022.0/first-steps/setup-3dcitydb.html#installation-steps-on-postgresql) for setting up a 3DCityDB instance.
4. Download the Energy ADE extension v2.0 from [here](https://github.com/3dcitydb/energy-ade-citydb/releases/tag/v2.0.0). Unzip the downloaded ZIP file into the `ade-extensions` folder which you can find inside the installation directory of your Importer/Exporter (see step 2).
    - After having unzipped, there should be a folder called `energy-ade-2.0.0` that contains three subdirectories: `3dcitydb`, `lib`, and `schema-mapping`.
5. Run the Importer/Exporter from step 2. Connect to your database created in step 3. Check the ADE table on the "Database" tab. Note that there is already a green check for the "Importer/Exporter" column.
6. Go to the "ADE Manager" tab of the Importer/Exporter. Under "ADE Registration", pick the path to the `energy-ade-2.0.0` folder (see step 4) as input for the "ADE extension package" input field. Afterwards, click on the "Register ADE" button to register the Energy ADE tables.
7. Go back to the "Database" tab of the Importer/Exporter and check the ADE table. Note that you now have two green checks and can start using the Energy ADE.

Took me 5min to set up the software. Steps 4 to 7 are also described in more detail in this [guide](https://3dcitydb-docs.readthedocs.io/en/version-2022.0/plugins/ade-manager/impexp-ade-extension.html). Simply replace Test ADE with Energy ADE while reading.

![image](https://user-images.githubusercontent.com/5517439/169680450-26c58f86-660d-42df-993e-f1bd8208c9cb.png)

**Comment by Ferkelcode** [comment]
It works now, thank you so much!!!

**Comment by clausnagel** [comment]
No, I don't know. I can import and export [FZKHouse-Lod2-EnergyADE.gml](https://github.com/3dcitydb/energy-ade-citydb/blob/main/resources/datasets/FZKHouse-Lod2-EnergyADE.gml) (I think you mean this dataset?) without issues. And I also have the correct feature types.

![image](https://user-images.githubusercontent.com/5517439/169700233-d895c729-a657-41e0-bb67-977b70381dd0.png)

Note that ADE feature types are neither supported by the VIS exporter or the Spreadsheet Plugin. So if your screenshot is taken from either operation, then yes, this is correct.

**Comment by clausnagel** [comment]
You should try and increase the available stack memory for your JVM.

Go to the installation directory of your Importer/Exporter, change to the `bin` folder and open the start script with a text editor (`impexp.bat` for Windows, `impexp` for Linux/UNIX).

Find the line defining `DEFAULT_JVM_OPTS` in the script (line 37 in `impexp.bat`, line 91 in `impexp`). Add the Java parameter `-Xss` to the list with an appropriate size (e.g., start with 1M). For example, for Windows, change line 37 to this:

```
set DEFAULT_JVM_OPTS="-Xms1G" "-Xss1M"
```

Rerun the Importer/Exporter afterwards.

Alternatively, try and reduce the number of maximal threads for the import operation (note that there is an identical preference for the export operation):

![image](https://user-images.githubusercontent.com/5517439/170130952-964774ac-1aab-41f9-b089-c109d6ec655a.png)

What is the current value of "maximal threads" in your Importer/Exporter?

**Comment by Ferkelcode** [comment]
Thank you so much for your answer.
My current value of 'maximal threads' is 16:
![image](https://user-images.githubusercontent.com/77849645/170186738-f412b853-e43a-45b9-8fa6-924269a551b1.png)

I have changed the impexp.bat file:
![image](https://user-images.githubusercontent.com/77849645/170186873-71330f41-5081-44ed-a2b0-a1b95c5f96a7.png)
and run the Importer/Exporter, and also changed the Maximal number of threads from 16 to 4:
![image](https://user-images.githubusercontent.com/77849645/170187004-ea27c56a-5132-43c4-a35f-5ec635fd22fc.png)
But keep the one of Export at 16
![image](https://user-images.githubusercontent.com/77849645/170187057-38252351-abbf-461e-9e50-d7bed3c8c78b.png)

I removed the ADE and registered again, but the problem is still same.
![image](https://user-images.githubusercontent.com/77849645/170187186-1812ac5f-1405-4de1-820f-a2c5a86918ad.png)


Since I was not so clear about the library, I have just tried to registered with different versions lib file from the EneragyADE for several times (removed and registered again):
![image](https://user-images.githubusercontent.com/77849645/170187439-f62d77c6-f798-4b96-9c1b-69f4fe811e67.png)
and 
![image](https://user-images.githubusercontent.com/77849645/170187492-d91b6e17-61da-494a-9acf-ca6828da9334.png)

But both have same result.

**Comment by clausnagel** [comment]
Please use the latest version 2.0.0 of the EnergyADE extension package: https://github.com/3dcitydb/energy-ade-citydb/releases/tag/v2.0.0

And please upload your dataset here so that we can use it for testing.

**Comment by Ferkelcode** [comment]
Thank you a lot.

I have removed the old libraries and tried with _energy-ade-citydb-2.0.0.jar_ and _energy-ade-citygml4j-1.0.4.jar_. But then the ADE doesn't appear anymore:
![image](https://user-images.githubusercontent.com/77849645/170227817-83bf22eb-3e96-4efa-9f29-0bb6a1269111.png)
Once I change back to the libraries of EnergyADE 1.3.0 or 1.2.3, it comes back again. Is this because I transformed the EnergyADE 1.0 but not 2.0.

Attached is the ADE that I put in ade-extensions folder. Thank you!
[ade-extensions.zip](https://github.com/3dcitydb/3dcitydb/files/8769673/ade-extensions.zip)

**Comment by clausnagel** [comment]
Well, you combine things which are not meant to be combined. As mentioned before, the EnergyADE extension of the 3DCityDB obly supports a subset/profile as defined by KIT. So, you cannot combine the JARs from this extension with a schema mapping of the full EnergyADE. Second, ADE extensions can only be used with specific versions of the Importer/Exporter. Versions 1.2 and 1.3 of the EnergyADE extension can only be used with versions 4.2 and 4.3 of the Importer/Exporter, but not with the latest version 5.x. That's why my 7 steps guide from above also included links to the download packages and test datasets that work together.

If you combine things that are not meant to work together, then running into issues is a very likely consequence. And it's not possible to support you with that.

Once more: If you want to use a full mapping of the EnergyADE, then you have to implement your own JAR files to have support in the Importer/Exporter.

**Comment by clausnagel** [comment]
Closing this issue now.
