### ISSUE TITLE
connection failed to database

### ISSUE THREAD

**Issue by WanliQianKolmostar** [3dcitydb/3dcitydb#92]
![Screenshot 2022-05-24 133848](https://user-images.githubusercontent.com/106110589/170098289-d5adeb35-e92f-40e8-9a09-62b291b60e46.png)

![image](https://user-images.githubusercontent.com/106110589/170098520-16ac69f6-8ff2-4fb7-8b6f-219f7cfe9ed6.png)
For some reasons I can't establish connections to the database. Could someone help me please? Thanks!

**Comment by clausnagel** [comment]
Sorry but there is not much help we can offer here. You have to make sure that you can reach and connect to your PostgreSQL database. Seems to be a network or configuration issue.
