### ISSUE TITLE
Limitation of the database modeling tool 'DbSchema' for 3DCityDB V5 

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#93]
[DbSchema ](https://dbschema.com/)is a good database design tool that could be used for the upcoming major release v5.  It comprises a number of nice features regarding e.g. flexible graphical layout, which is not supported by pgModeler (which is currently used for the PostgreSQL version). 

However, the DbSchema has a critical limitation on the support of geometry data type. You are not able to define subtype type modifiers (e.g. POINTZ, LINESTRING, POLYGON, POLYGONZ) for geometry columns. For example, the following column definition using the `POINTZ` type modifier is not supported by DbSchema.

``` sql
CREATE  TABLE citydb.property ( 
       ....
	val_implicitgeom_refpoint geometry(POINTZ),
       ....
 );
```

Only the following definition is possible.
``` sql
CREATE  TABLE citydb.property ( 
       ....
	val_implicitgeom_refpoint geometry,
       ....
 );
```
Should this limitation prevent us from using DbSchema for the 3DCityDB v5?

**Comment by yaozhihang** [comment]
Well, pgModeler supports the type modifiers (e.g. POINTZ, LINESTRING, POLYGON, POLYGONZ) for geometry columns. The current [schema scripts](https://github.com/3dcitydb/3dcitydb/blob/master/postgresql/SQLScripts/SCHEMA/SCHEMA.sql) were automatically derived from the pgModeler model and use the geometry type modifiers explictly. If we consider the definition of type modifiers is important, we have to use pgModeler rather than DbSchema in spite of its two advantages, which are just related to graphic layouts.

**Comment by yaozhihang** [comment]
OK, I've investigated futher the DbSchema tool. It allows to define new column data types e.g.  `geometry(POINTZ)`. So, DbSchema should be sufficient enough for our 3DCityDB v5

**Comment by clausnagel** [comment]
Good to see the progress. The tool discussion should however not block the alpha release. If necessary we have to adjust the scripts manually.
