### ISSUE TITLE
Drop the tables “citymodel” and “cityobject_member” in 3DCityDB v5

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#94]
Could we drop the tables “citymodel” and “cityobject_member” and store the information in the new “feature” and “property” tables?

**Comment by yaozhihang** [comment]
OK, so i think we should then remove the `citymodel_id` column from the `appearance` table and rename the `cityobject_id` column to `feature_id` referencing to the `id` column of the `feature` table.
![image](https://user-images.githubusercontent.com/5942971/171867221-103bffec-4954-421d-bad2-a22bb73d9cbb.png)

**Comment by yaozhihang** [comment]
OK, we can then drop the two columns `cityobject_id` and `citymodel_id` from the `appearance` table
![image](https://user-images.githubusercontent.com/5942971/171868377-b5e42efa-f77e-4146-b770-a8f7b26fd0b5.png)

**Comment by yaozhihang** [comment]
agree

**Comment by clausnagel** [comment]
In an offline discussion @yaozhihang and me figured that there could be use cases for having a separate `citymodel` table. A `CityModel` typically represents a single dataset. Thus, the `citymodel` table could be used to implement a document-based access to the city objects stored in `feature`. For instance, the entries in `citymodel` could be used to arrange all city objects in a 2x2km grid. This would allow to easily export each grid cell as separate dataset and also to define cell-based update and management processes.

We are not aware that the `citymodel` table of the 3DCityDB v4 is actually used this way. The current Importer/Exporter at least doesn't support `citymodel`. Nevertheless, we propose to keep the `citymodel` table for the alpha release. We will leave this issue open to continue the disucssion about possibly dropping the `citymodel` table at a later point in time.

**Comment by yaozhihang** [comment]
One more thought: The `cityobject_member` table of the 3DCityDB v4  could be dropped and add an FK column `citymodel_id` to the `feature` table instead, since the citymodel and cityobject/feature mostly have a 1: n relationship.

**Comment by muratkendir** [comment]
My personal idea is that citymodel table is able to provide multi advantages to the digital twin projects. First one is, it is possible to use different datasets (or combine datasets) which have different coordinate systems. Of course, there are some obligations / bottlenecks while using same dataset with different coordinate systems (Especially when one of the CS is geographic and other one is projected). I agree that it is not an easy work progress to handle this kind of datasets, but it is also predictable that it is possible to join digital twins on same 3dcitydb instance with citymodel table. Second possible advantage is that combining datasets which derived / collected in different time intervals. From my former experiences, i learned that collected data from a whole city should be accomplished nearly same times. For exp. assume that we have collected/derived building data of a city in 2018. At 2022, a private company provided digital elevation model (DEM) of same city to us and we want to combine this DEM data and building data on same 3DCityDB database. Everything would be work fine, except some buildings which may demolished or reconstructed between 2018 - 2022. You may experience/view pits below buildings or hills intersecting with buildings. As i said, these are my personal thoughts and also need to say that citymodel and cityobject_member tables are not considered in v4->v5 upgrade scripts, they are dropped/ignored.

**Comment by yaozhihang** [comment]
In an offline discussion with @clausnagel and @thomashkolbe , we decide to drop the `citymodel` table for the alpha version. This also means the following two small changes in the `appearance` table
1. new column `is_global`
2. rename `cityobject_id` to `feature_id`
