### ISSUE TITLE
Redesign of the GEOMETRY table for 3DCityDB v5

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#95]
More details: [3DCityDB_Geometry_Table.pdf](https://github.com/3dcitydb/3dcitydb/files/8803959/3DCityDB_Geometry_Table.pdf)

**Comment by clausnagel** [comment]
"may" or "will" cause issues? 

I also like "geometries" as name. Would mean to also use "features", "properties" and "appearances". But why not?

**Comment by muratkendir** [comment]
In QGIS, GeoPackage and PostGIS domains they are mostly renamed as "geom". How about to rename as "geom"?
