### ISSUE TITLE
Consistent property FK column naming convention

### ISSUE THREAD

**Issue by yaozhihang** [3dcitydb/3dcitydb#99]
Most FK columns (e.g. `val_grid_coverage`, `val_appearance`, `val_dynamizer`) follows the naming convention "val_[referencedTable]". An exception is `val_implicitgeom_id`. We should make it consistent by renaming this column to `val_implicitgeom` or add the suffix `_id` to the other FK columns. 

I prefer to add the `_id` suffix to the these FK columns. This allows to quickly distinguish the inline and referenced property columns based on their names.

**Comment by muratkendir** [comment]
Actually i have noticed same out or ordinary column name, but i think most of columns starts with "val_" prefix already used as references. My opinion is just removing "_id" suffix from "val_implicitgeom_id" will fix this.

**Comment by clausnagel** [comment]
I think the prefix `val_` should be used for columns that store the value inline. For FK columns referencing another table like appearance, implicit_geometry or geometry, we should stick to the naming convention for FK columns that we already have (so, no `val_` prefix but an `_id` suffix).

**Comment by thomashkolbe** [comment]
The reason why these columns have a `val_` prefix is to distinguish them from the other columns that contain organizational, structural, or meta information. The `val_` columns carry the property value (no matter if it is a link to another object or an in-situ value). The best way to stick with the older naming convention would be to add the suffix `_id` to those columns representing a property value that is a reference to another table like `val_grid_coverage` ->  `val_grid_coverage_id`, `val_dynamizer` -> `val_dynamizer_id` etc.

**Comment by clausnagel** [comment]
Yes, sounds like a good compromise for me. And matches the initial proposal of @yaozhihang. I can see the benefit of using `val_` as prefix for all columns storing values independent of whether the value is inline or by reference.

**Comment by yaozhihang** [comment]
Done with [b4b7e6c](https://github.com/3dcitydb/3dcitydb/commit/b4b7e6c50298a7a7234c09a903e6406558690b57)
